/**
 * `UNIT_BY_KEY` — the unit each catalogued point key is seeded with, keyed by
 * code. **Read by `point-keys-seed.ts`'s `keysForDomain`** as
 * `UNIT_BY_KEY[code] ?? null`; nothing else imports it.
 *
 * **Why it lives here and not beside its one reader (E4.1c PR 2b, a §4.5
 * gate).** `point-keys-seed.ts` reached 988 lines after PR 2a's 19 entries,
 * and PR 2b's ten mechanical / HVAC / facility codes cross AGENTS.md §4.5's
 * 1000-line cap, which `.githooks/pre-commit.mjs` reads WHOLE-FILE and blocks.
 * The table is the part that grows with every pack and carries no logic, so
 * it moved whole — byte-identical rows, the same declaration line with an
 * `export` in front — and the seed's docblocks, `keysForDomain` and the
 * `INSERT` stay where they were. The PR 2a migration review named this split
 * as its High.
 *
 * **`tests/f3.39-global-point-key-vocabulary.test.ts` reads this file BY PATH
 * (`UNITS_REL`) and parses the table as text** with
 * `/const UNIT_BY_KEY: Record<string, string> = \{([\s\S]*?)\n\};/` — the
 * top-level `tests/` project has no workspace dependency on `@bms/db`. Keep
 * the declaration line and the `};` closer exactly as they are: a widened type
 * annotation or a `satisfies` clause makes the guard parse NOTHING, and its
 * anti-vacuity floor is what would catch that. Every code in every
 * `*_POINT_KEYS` array needs a row here — a missing one seeds a NULL unit
 * that `seedPointKeyCatalog`'s `COALESCE` then makes permanent for the row's
 * lifetime (the seed's docblock states the trade).
 *
 * The empty string is a deliberate "no unit" (`pf`, `breaker_main`, a count,
 * a money point whose currency is the organization's — plan E4.1c Q8); it is
 * not the same as an absent row.
 */
export const UNIT_BY_KEY: Record<string, string> = {
  voltage_l1_v: "V",
  current_a: "A",
  kw: "kW",
  kvar: "kVAr",
  pf: "",
  breaker_main: "",
  supply_air_temp_c: "°C",
  return_air_temp_c: "°C",
  fan_rpm: "RPM",
  fan_speed_pct: "%",
  chw_flow_lps: "L/s",
  chw_supply_temp_c: "°C",
  chw_return_temp_c: "°C",
  compressor_ok: "",
  cooling_kw: "kW",
  load_pct: "%",
  output_voltage_v: "V",
  output_freq_hz: "Hz",
  battery_v: "V",
  battery_temp_c: "°C",
  backup_min: "min",
  health_pct: "%",
  rack_kw: "kW",
  rack_temp_c: "°C",
  pdu_a_status: "",
  pdu_b_status: "",
  pdu_util_pct: "%",
  outlets_used: "",
  temperature_c: "°C",
  humidity_pct: "%",
  leak_state: "",
  smoke_state: "",
  frequency_hz: "Hz",
  kwh_today: "kWh",
  // `F3.41` — `METERED_PUMPING_POINT_KEYS`. Every unit is read from
  // `phe-catalog.json`'s own `UnitCode` column rather than inferred from the
  // code's name, so the catalog row and the `asset_points` row `phe-pilot-seed`
  // writes beside it agree. `chlorine_pump_on` is a binary and takes `""`, the
  // way `pf` and `breaker_main` above already spell an unset unit — NOT a
  // missing entry, which would seed NULL and overwrite the real value on every
  // `compose up`.
  kwh_total: "kWh",
  kva: "kVA",
  current_ir: "A",
  current_iy: "A",
  current_ib: "A",
  voltage_vry: "V",
  voltage_vyb: "V",
  voltage_vbr: "V",
  voltage_vrn: "V",
  voltage_vyn: "V",
  voltage_vbn: "V",
  chlorine_pump_on: "",
  // `F2.11` — `ELECTRICAL_CLASS_POINT_KEYS`. Every unit is read from
  // `docs/electrical-derived-taglist-v1.md`'s own Unit column, per ADR 0051
  // Amendment 6 decision 4 — `0/1`, `enum`, `code`, `tap`, `count` and `—`
  // all map to `""`, the way `pf`, `breaker_main` and `outlets_used` above
  // already spell an unset unit, and NEVER a missing entry, which would
  // seed NULL and revert a global administrator's correction on every
  // `compose up`. `kVAR`/`kVARh` in the source file are spelled `kVAr`/
  // `kVArh` here to match `kvar` above, and `rpm` is spelled `RPM` to match
  // `fan_rpm` above (owner ruling 2026-09-02).
  //
  // §1 feeder / incomer
  current_in: "A",
  kvah_total: "kVAh",
  kvarh_total: "kVArh",
  demand_kw: "kW",
  max_demand_kw: "kW",
  max_demand_kva: "kVA",
  thd_v_pct: "%",
  thd_i_pct: "%",
  voltage_unbalance_pct: "%",
  current_unbalance_pct: "%",
  breaker_trip: "",
  breaker_spring_charged: "",
  relay_trip_code: "",
  earth_fault_state: "",
  meter_comms_ok: "",
  site_kw: "kW", // F2.8: derived, formula in electrical-feeder.ts
  it_kw: "kW", // F2.8: derived, formula in electrical-feeder.ts
  pue: "", // F2.8: derived, formula in electrical-feeder.ts — dimensionless ratio, spelled like pf
  // §2 transformer
  top_oil_temp_c: "°C",
  winding_temp_c: "°C",
  winding_temp_r_c: "°C",
  winding_temp_y_c: "°C",
  winding_temp_b_c: "°C",
  ambient_temp_c: "°C",
  oil_level_pct: "%",
  oil_level_low: "",
  buchholz_alarm: "",
  buchholz_trip: "",
  prv_operated: "",
  oti_alarm: "",
  oti_trip: "",
  wti_alarm: "",
  wti_trip: "",
  tap_position: "",
  oltc_in_progress: "",
  oltc_operation_count: "",
  cooling_fan_status: "",
  cooling_pump_status: "",
  dga_h2_ppm: "ppm",
  dga_c2h2_ppm: "ppm",
  dga_ch4_ppm: "ppm",
  dga_co_ppm: "ppm",
  oil_moisture_ppm: "ppm",
  lv_load_pct: "%",
  oil_bdv_kv: "kV",
  oil_moisture_lab_ppm: "ppm",
  silica_gel_state: "",
  insulation_resistance_mohm: "MΩ",
  oil_rise_over_ambient_c: "°C", // F2.12: derived, formula in electrical-transformer.ts
  // §3 DG set
  dg_status: "",
  dg_mode: "",
  dg_on_load: "",
  dg_alarm: "",
  dg_shutdown: "",
  dg_alarm_code: "",
  mains_available: "",
  engine_speed_rpm: "RPM",
  oil_pressure_bar: "bar",
  coolant_temp_c: "°C",
  oil_temp_c: "°C",
  exhaust_temp_c: "°C",
  fuel_level_pct: "%",
  bulk_fuel_level_pct: "%",
  fuel_rate_lph: "L/hr",
  fuel_totalizer_l: "L",
  charger_alternator_v: "V",
  coolant_level_low: "",
  run_hours_h: "h",
  start_count: "",
  failed_start_count: "",
  gen_voltage_vry: "V",
  gen_voltage_vyb: "V",
  gen_voltage_vbr: "V",
  gen_current_ir: "A",
  gen_current_iy: "A",
  gen_current_ib: "A",
  gen_frequency_hz: "Hz",
  gen_kw: "kW",
  gen_kva: "kVA",
  gen_pf: "",
  gen_kwh_total: "kWh",
  service_due_h: "h",
  emergency_stop_state: "",
  canopy_temp_c: "°C",
  specific_fuel_l_kwh: "L/kWh", // F2.12: derived, formula in electrical-dg-set.ts
  unplanned_run_flag: "", // F2.12: derived, formula in electrical-dg-set.ts
  // §4 UPS
  ups_status: "",
  ups_alarm: "",
  ups_alarm_code: "",
  on_battery: "",
  on_bypass: "",
  input_voltage_v: "V",
  input_frequency_hz: "Hz",
  output_current_a: "A",
  output_kw: "kW",
  output_kva: "kVA",
  battery_current_a: "A",
  battery_charge_pct: "%",
  battery_time_on_s: "s",
  battery_replace_flag: "",
  battery_last_test: "",
  rectifier_ok: "",
  inverter_ok: "",
  fan_ok: "",
  cell_voltage_min_v: "V",
  cell_voltage_max_v: "V",
  impedance_test_result: "",
  load_headroom_pct: "%", // F2.12: derived, formula in electrical-ups.ts
  cell_voltage_spread_v: "V", // F2.12: derived, formula in electrical-ups.ts
  // §5 solar PV
  inv_status: "",
  inv_fault: "",
  inv_event_code: "",
  dc_voltage_v: "V",
  dc_current_a: "A",
  dc_power_kw: "kW",
  ac_power_kw: "kW",
  ac_kva: "kVA",
  ac_pf: "",
  ac_frequency_hz: "Hz",
  ac_voltage_vry: "V",
  ac_voltage_vyb: "V",
  ac_voltage_vbr: "V",
  ac_current_ir: "A",
  ac_current_iy: "A",
  ac_current_ib: "A",
  energy_total_kwh: "kWh",
  energy_today_kwh: "kWh",
  cabinet_temp_c: "°C",
  irradiance_wm2: "W/m²",
  module_temp_c: "°C",
  string_current_a: "A",
  insulation_resistance_kohm: "kΩ",
  grid_export_kw: "kW",
  soiling_loss_pct: "%",
  inverter_efficiency_pct: "%", // F2.12: derived, formula in electrical-solar-pv.ts
  // §6 capacitor bank / APFC
  apfc_status: "",
  apfc_alarm: "",
  target_pf: "",
  actual_pf: "",
  steps_on_count: "",
  step_state: "",
  kvar_connected: "kVAr",
  kvar_required: "kVAr",
  bus_voltage_v: "V",
  panel_temp_c: "°C",
  step_operation_count: "",
  capacitor_current_a: "A",
  step_fault_state: "",
  // `E5.1` — `WATER_CLASS_POINT_KEYS` (ADR 0040 decision 2). Every unit is
  // read from `docs/e5.1-derived-taglist-v1.md`'s own Unit column, exactly
  // §4.4 of `docs/plans/e5.1-water-domain-pack.md` spells it. `""` — never a
  // missing entry, which would seed NULL and revert a global administrator's
  // correction on every `compose up` — is the spelling for the eleven `0/1`
  // rows and for `cycles_of_concentration`, a dimensionless ratio. `pH`,
  // `Hazen` and `SDI15` are named units an operator reads, not `""` (ADR
  // 0051 Amendment 6 decision 4 maps only 0/1, enum, code, tap and count to
  // the empty string). `µS/cm` below is `U+00B5` MICRO SIGN, not `U+03BC`
  // GREEK SMALL LETTER MU — verified against the tag list's own codepoint —
  // and that value is permanent the moment this seed runs once.
  //
  // §1 WTP
  raw_water_flow_klh: "KL/hr",
  raw_turbidity_ntu: "NTU",
  raw_ph: "pH",
  settled_turbidity_ntu: "NTU",
  filtered_turbidity_ntu: "NTU",
  filter_dp_bar: "bar",
  backwash_status: "",
  coagulant_dose_lph: "L/hr",
  chlorine_dose_lph: "L/hr",
  treated_cl2_residual_mgl: "mg/L",
  treated_water_flow_klh: "KL/hr",
  clearwell_level_pct: "%",
  clarifier_sludge_level_pct: "%",
  treated_conductivity_uscm: "µS/cm",
  intake_pump_current_a: "A",
  intake_pump_status: "",
  raw_color_hazen: "Hazen",
  raw_alkalinity_mgl: "mg/L",
  recovery_pct: "%", // E5.1: derived, formula in water-wtp.ts / water-ro.ts
  turbidity_removal_pct: "%", // E5.1: derived, formula in water-wtp.ts
  // §2 RO
  feed_flow_klh: "KL/hr",
  permeate_flow_klh: "KL/hr",
  reject_flow_klh: "KL/hr",
  feed_pressure_bar: "bar",
  stage1_dp_bar: "bar",
  feed_conductivity_uscm: "µS/cm",
  permeate_conductivity_uscm: "µS/cm",
  feed_ph: "pH",
  feed_orp_mv: "mV",
  feed_temp_c: "°C",
  hp_pump_current_a: "A",
  hp_pump_status: "",
  cip_status: "",
  antiscalant_dose_lph: "L/hr",
  feed_sdi: "SDI15",
  cartridge_filter_dp_bar: "bar",
  salt_rejection_pct: "%", // E5.1: derived, formula in water-ro.ts
  // §3 softener
  inlet_flow_klh: "KL/hr",
  outlet_flow_totalizer_kl: "KL",
  outlet_hardness_mgl: "mg/L",
  inlet_hardness_mgl: "mg/L",
  vessel_dp_bar: "bar",
  regen_status: "",
  brine_tank_level_pct: "%",
  salt_consumption_kg: "kg",
  outlet_conductivity_uscm: "µS/cm",
  // §4 cooling tower
  supply_temp_c: "°C",
  return_temp_c: "°C",
  ambient_wetbulb_c: "°C",
  circ_flow_klh: "KL/hr",
  makeup_flow_klh: "KL/hr",
  blowdown_flow_klh: "KL/hr",
  basin_level_pct: "%",
  circ_conductivity_uscm: "µS/cm",
  makeup_conductivity_uscm: "µS/cm",
  circ_ph: "pH",
  circ_orp_mv: "mV",
  fan_status: "",
  fan_current_a: "A",
  circ_pump_status: "",
  circ_pump_current_a: "A",
  inhibitor_dose_lph: "L/hr",
  circ_tds_mgl: "mg/L",
  range_c: "°C", // E5.1: derived, formula in water-cooling-tower.ts
  approach_c: "°C", // E5.1: derived, formula in water-cooling-tower.ts
  cycles_of_concentration: "", // E5.1: derived, formula in water-cooling-tower.ts
  makeup_pct: "%", // E5.1: derived, formula in water-cooling-tower.ts
  // §5 STP
  influent_flow_klh: "KL/hr",
  effluent_flow_klh: "KL/hr",
  aeration_do_mgl: "mg/L",
  mlss_mgl: "mg/L",
  effluent_turbidity_ntu: "NTU",
  effluent_tss_mgl: "mg/L",
  effluent_ph: "pH",
  effluent_cl2_residual_mgl: "mg/L",
  effluent_bod_mgl: "mg/L",
  effluent_cod_mgl: "mg/L",
  blower_status: "",
  blower_current_a: "A",
  ras_flow_klh: "KL/hr",
  eq_tank_level_pct: "%",
  treated_tank_level_pct: "%",
  mbr_tmp_bar: "bar",
  uv_status: "",
  // §6 ETP
  neutralization_ph: "pH",
  dosing_acid_lph: "L/hr",
  dosing_alkali_lph: "L/hr",
  bio_mlss_mgl: "mg/L",
  bio_do_mgl: "mg/L",
  settling_tss_mgl: "mg/L",
  clarifier_turbidity_ntu: "NTU",
  discharge_flow_klh: "KL/hr",
  discharge_ph: "pH",
  oil_grease_mgl: "mg/L",
  sludge_holding_level_pct: "%",
  filter_press_status: "",
  transfer_pump_status: "",
  guard_pond_level_pct: "%",
  // `E5.2` / ADR 0053 decision 3 — `MECHANICAL_CLASS_POINT_KEYS` +
  // `HVAC_CLASS_POINT_KEYS`, 107 entries, exactly as §4.4 of
  // `docs/plans/e5.2-mechanical-domain-pack.md` spells them. `""` — never a
  // missing entry, which would seed NULL and revert a global administrator's
  // correction on every `compose up` — is the spelling for every `0/1`,
  // `enum` and `code` row, and for the two dimensionless ratios (`cop`,
  // `steam_to_fuel_ratio`). `°` is `U+00B0` on every `°C` code below, and `³`
  // in `fad_m3h` / `specific_power_kw_m3min` is `U+00B3` SUPERSCRIPT THREE —
  // both verified against the tag list's own codepoint, and permanent the
  // moment this seed runs once. The twenty reused codes
  // (`current_a`, `kw`, `kwh_total`, `run_hours_h`, `start_count`,
  // `winding_temp_c`, `insulation_resistance_mohm`, `oil_temp_c`,
  // `oil_pressure_bar`, `service_due_h`, `chw_supply_temp_c`,
  // `chw_return_temp_c`, `chw_flow_lps`, `compressor_ok`, `cooling_kw`,
  // `supply_air_temp_c`, `return_air_temp_c`, `fan_speed_pct`, `fan_rpm`,
  // `fan_current_a`) and the boiler's reused `fuel_level_pct` are NOT
  // redeclared here — they already have an entry above.
  //
  // §1 pump set
  pump_status: "",
  pump_mode: "",
  pump_trip: "",
  suction_pressure_bar: "bar",
  discharge_pressure_bar: "bar",
  flow_klh: "KL/hr",
  de_bearing_temp_c: "°C",
  nde_bearing_temp_c: "°C",
  vibration_mms: "mm/s",
  seal_leak_state: "",
  dry_run_state: "",
  head_m: "m", // E5.2: derived, formula in mechanical-pump.ts
  specific_energy_kwh_kl: "kWh/KL", // E5.2: derived, formula in mechanical-pump.ts
  // §2 motor + VFD
  vfd_status: "",
  vfd_ready: "",
  vfd_fault: "",
  vfd_fault_code: "",
  vfd_output_freq_hz: "Hz",
  vfd_speed_ref_pct: "%",
  vfd_output_current_a: "A",
  vfd_output_voltage_v: "V",
  vfd_dc_bus_v: "V",
  vfd_torque_pct: "%",
  vfd_power_kw: "kW",
  vfd_kwh_total: "kWh",
  vfd_heatsink_temp_c: "°C",
  motor_temp_c: "°C",
  vfd_run_hours_h: "h",
  // §3 air compressor
  comp_status: "",
  comp_load_state: "",
  comp_fault: "",
  comp_warning: "",
  outlet_pressure_bar: "bar",
  pressure_setpoint_bar: "bar",
  element_outlet_temp_c: "°C",
  intake_filter_dp_mbar: "mbar",
  oil_separator_dp_bar: "bar",
  loaded_hours_h: "h",
  motor_current_a: "A",
  dryer_dewpoint_c: "°C",
  dryer_status: "",
  receiver_pressure_bar: "bar",
  fad_m3h: "m³/hr",
  load_factor_pct: "%", // E5.2: derived, formula in mechanical-compressor.ts
  specific_power_kw_m3min: "kW/(m³/min)", // E5.2: derived, formula in mechanical-compressor.ts
  // §7 boiler (fuel_level_pct reused from the DG set, §12 ruling 1, not
  // redeclared)
  boiler_status: "",
  boiler_trip: "",
  steam_pressure_bar: "bar",
  steam_temp_c: "°C",
  steam_flow_kgh: "kg/hr",
  steam_totalizer_kg: "kg",
  drum_level_pct: "%",
  feedwater_flow_kgh: "kg/hr",
  feedwater_temp_c: "°C",
  feedwater_tds_ppm: "ppm",
  feed_pump_status: "",
  fuel_flow_kgh: "kg/hr",
  fuel_totalizer_kg: "kg",
  flue_gas_temp_c: "°C",
  flue_o2_pct: "%",
  flue_co_ppm: "ppm",
  combustion_air_temp_c: "°C",
  furnace_draft_mmwc: "mmWC",
  blowdown_state: "",
  boiler_water_ph: "pH",
  blowdown_tds_ppm: "ppm",
  steam_to_fuel_ratio: "", // E5.2: derived, formula in mechanical-boiler.ts
  excess_air_pct: "%", // E5.2: derived, formula in mechanical-boiler.ts
  // §4 chiller
  chiller_status: "",
  chiller_alarm: "",
  chiller_fault_code: "",
  chw_setpoint_c: "°C",
  cw_entering_temp_c: "°C",
  cw_leaving_temp_c: "°C",
  cw_flow_lps: "L/s",
  evap_pressure_bar: "bar",
  cond_pressure_bar: "bar",
  evap_approach_c: "°C",
  cond_approach_c: "°C",
  compressor_load_pct: "%",
  compressor_current_a: "A",
  discharge_temp_c: "°C",
  refrigerant_charge_pct: "%",
  cooling_load_tr: "TR", // E5.2: derived, formula in hvac-chiller.ts
  kw_per_tr: "kW/TR", // E5.2: derived, formula in hvac-chiller.ts
  cop: "", // E5.2: derived, formula in hvac-chiller.ts
  chw_delta_t_c: "°C", // E5.2: derived, formula in hvac-chiller.ts
  cw_delta_t_c: "°C", // E5.2: derived, formula in hvac-chiller.ts
  // §6 AHU
  ahu_status: "",
  ahu_fault: "",
  supply_air_temp_sp_c: "°C",
  mixed_air_temp_c: "°C",
  outdoor_air_temp_c: "°C",
  return_air_rh_pct: "%",
  supply_air_rh_pct: "%",
  duct_static_pa: "Pa",
  duct_static_sp_pa: "Pa",
  return_fan_speed_pct: "%",
  chw_valve_pct: "%",
  oa_damper_pct: "%",
  ra_damper_pct: "%",
  filter_dp_pa: "Pa",
  filter_dirty_state: "",
  return_air_co2_ppm: "ppm",
  fire_trip_state: "",
  sat_deviation_c: "°C", // E5.2: derived, formula in hvac-ahu.ts
  coil_delta_t_c: "°C", // E5.2: derived, formula in hvac-ahu.ts
  // E5.3 (ADR 0054 decision 3) — the facility pack's 104 codes, from
  // packages/shared/src/facility-point-keys.ts, in the tag list's section
  // order. `""` and NEVER a missing entry for every 0/1, count, enum, code,
  // text, floor and date row and for the one dimensionless ratio: `?? null`
  // seeds NULL on a NEW row. It cannot overwrite a real one —
  // `seedPointKeyCatalog` writes `COALESCE(bms.point_keys.unit,
  // EXCLUDED.unit)`, so the next boot repairs a NULL once the entry exists.
  // The failure that IS permanent is a WRONG spelling, which is why the
  // codepoint check and not the presence check is the real gate: ° is U+00B0,
  // µ is U+00B5 (MICRO SIGN, E5.1's µS/cm, never U+03BC), ³ is U+00B3.
  // §1 lighting zone — 15
  lighting_state: "",
  lighting_level_pct: "%",
  lighting_mode: "",
  lighting_scene: "",
  occupancy_state: "",
  illuminance_lux: "lux",
  illuminance_sp_lux: "lux",
  lamp_fault_count: "",
  driver_fault_state: "",
  emergency_test_state: "",
  emergency_battery_ok: "",
  zone_kw: "kW",
  zone_kwh_total: "kWh",
  burn_hours_h: "h",
  schedule_active: "",
  // §2 fire alarm panel — 23 (smoke_state is the control-room array's)
  fire_alarm_state: "",
  fire_fault_state: "",
  fire_supervisory_state: "",
  fire_isolate_state: "",
  fire_prealarm_state: "",
  panel_ac_ok: "",
  panel_battery_ok: "",
  panel_earth_fault: "",
  panel_comms_ok: "",
  zone_alarm_state: "",
  zone_fault_state: "",
  zone_isolated_state: "",
  active_alarm_count: "",
  active_fault_count: "",
  sounder_active: "",
  sounder_silenced: "",
  fire_pump_status: "",
  jockey_pump_status: "",
  hydrant_header_pressure_bar: "bar",
  fire_tank_level_pct: "%",
  sprinkler_flow_state: "",
  suppression_released_state: "",
  weekly_test_done: "",
  // §3 access door — 17 (16 rows + 1 derived)
  door_state: "",
  lock_state: "",
  door_forced_state: "",
  door_held_state: "",
  door_mode: "",
  reader_ok: "",
  controller_comms_ok: "",
  controller_tamper: "",
  controller_ac_ok: "",
  controller_battery_ok: "",
  access_granted_count: "",
  access_denied_count: "",
  rex_count: "",
  fire_release_state: "",
  lockdown_state: "",
  turnstile_status: "",
  denied_ratio_pct: "%", // E5.3: derived, formula in facility-access-door.ts
  // §4 occupancy zone — 10 (occupancy_state is §1's; 9 rows + 1 derived)
  occupancy_count: "",
  occupancy_capacity: "",
  entry_count: "",
  exit_count: "",
  desk_occupied_count: "",
  zone_temp_c: "°C",
  zone_rh_pct: "%",
  zone_temp_sp_c: "°C",
  sensor_battery_pct: "%",
  occupancy_pct: "%", // E5.3: derived, two formulas — occupancy zone and parking level
  // §5 parking level — 14 (entry_count and exit_count are §4's)
  bays_total: "",
  bays_occupied: "",
  bays_free: "",
  ev_bays_free: "",
  entry_barrier_state: "",
  exit_barrier_state: "",
  barrier_fault: "",
  co_ppm: "ppm",
  no2_ppm: "ppm",
  jet_fan_status: "",
  jet_fan_fault: "",
  guidance_comms_ok: "",
  ev_charger_kw: "kW",
  ev_charger_kwh_total: "kWh",
  // §7 BAS gateway — 12 (leak_state is the control-room array's)
  device_online: "",
  last_seen_age_s: "s",
  comms_error_count: "",
  points_stale_count: "",
  cpu_pct: "%",
  memory_pct: "%",
  enclosure_temp_c: "°C",
  supply_voltage_v: "V",
  ups_on_battery: "",
  door_open_state: "",
  rtc_drift_s: "s",
  firmware_version: "",
  // §6 IAQ node — 13, the environment array (11 rows + 2 derived)
  co2_ppm: "ppm",
  pm25_ugm3: "µg/m³",
  pm10_ugm3: "µg/m³",
  tvoc_ugm3: "µg/m³",
  ch2o_ugm3: "µg/m³",
  o3_ppb: "ppb",
  no2_ppb: "ppb",
  outdoor_pm25_ugm3: "µg/m³",
  outdoor_co2_ppm: "ppm",
  sensor_online: "",
  microbial_count_cfu: "CFU/m³",
  co2_above_outdoor_ppm: "ppm", // E5.3: derived, formula in environment-iaq-node.ts
  pm25_indoor_outdoor_ratio: "", // E5.3: derived, dimensionless (the `cop` spelling)
  // §8a lift — 74 (72 rows + 2 derived); controller_comms_ok, motor_current_a,
  // motor_temp_c, kw, kwh_total, run_hours_h are reused, not redeclared here
  lift_in_service: "",
  lift_mode: "",
  lift_fault: "",
  lift_fault_code: "",
  lift_fault_count: "",
  fire_recall_state: "",
  fire_operation_state: "",
  emergency_power_mode: "",
  ard_state: "",
  passenger_alarm: "",
  entrapment_state: "",
  intercom_call_active: "",
  car_position_floor: "",
  car_position_m: "m",
  car_direction: "",
  car_moving: "",
  car_speed_ms: "m/s",
  car_load_pct: "%",
  car_load_kg: "kg",
  overload_state: "",
  full_load_bypass_state: "",
  levelling_error_mm: "mm",
  hall_calls_pending: "",
  car_calls_pending: "",
  next_stop_floor: "",
  car_door_state: "",
  landing_door_state: "",
  door_zone_state: "",
  door_cycle_count: "",
  door_reversal_count: "",
  door_open_time_s: "s",
  door_fault_state: "",
  door_motor_current_a: "A",
  drive_status: "",
  drive_fault_code: "",
  drive_heatsink_temp_c: "°C",
  dc_bus_v: "V",
  brake_state: "",
  brake_temp_c: "°C",
  brake_fault_state: "",
  rope_brake_state: "",
  hydraulic_oil_temp_c: "°C",
  hydraulic_oil_level_low: "",
  hydraulic_pressure_bar: "bar",
  regen_kw: "kW",
  machine_room_temp_c: "°C",
  machine_room_humidity_pct: "%",
  pit_water_state: "",
  pit_light_state: "",
  shaft_temp_c: "°C",
  safety_chain_ok: "",
  governor_tripped: "",
  terminal_limit_state: "",
  car_light_state: "",
  car_fan_state: "",
  car_temp_c: "°C",
  vibration_x_mg: "mg",
  vibration_y_mg: "mg",
  vibration_z_mg: "mg",
  max_accel_ms2: "m/s²",
  max_jerk_ms3: "m/s³",
  noise_dba: "dB(A)",
  trip_count: "",
  floor_km_total: "km",
  passenger_count: "",
  waiting_time_avg_s: "s",
  waiting_time_max_s: "s",
  annual_inspection_due: "",
  rope_condition: "",
  brake_test_result: "",
  buffer_test_result: "",
  ard_battery_test: "",
  door_reversal_ratio_pct: "%", // E5.3: derived, formula in mechanical-lift.ts
  kwh_per_trip: "kWh", // E5.3: derived, formula in mechanical-lift.ts
  // §8b escalator — 28 (27 rows + 1 derived); controller_comms_ok,
  // motor_current_a, motor_temp_c, brake_state, brake_temp_c, passenger_count,
  // kw, kwh_total, run_hours_h, start_count, vibration_mms,
  // annual_inspection_due, brake_test_result are reused, not redeclared here
  esc_status: "",
  esc_direction: "",
  esc_mode: "",
  esc_fault: "",
  esc_fault_code: "",
  esc_emergency_stop: "",
  safety_circuit_ok: "",
  safety_device_tripped: "",
  step_speed_ms: "m/s",
  handrail_speed_l_ms: "m/s",
  handrail_speed_r_ms: "m/s",
  handrail_speed_dev_pct: "%", // E5.3: derived, sortOrder 39 — §12 ruling 3
  gearbox_temp_c: "°C",
  gearbox_oil_level_low: "",
  aux_brake_tripped: "",
  step_chain_tension_ok: "",
  drive_chain_ok: "",
  missing_step_state: "",
  comb_plate_state: "",
  skirt_switch_state: "",
  handrail_inlet_state: "",
  passenger_sensor_state: "",
  machine_space_temp_c: "°C",
  truss_water_state: "",
  lubrication_fault: "",
  standby_hours_h: "h",
  step_chain_elongation_pct: "%",
  kwh_per_run_hour: "kWh/h", // E5.3: derived, formula in mechanical-escalator.ts — §12 ruling 7
  // `E4.1c` / ADR 0070 decision 8 — `SUSTAINABILITY_ELECTRICAL_POINT_KEYS` +
  // `SUSTAINABILITY_WATER_POINT_KEYS`, 19 entries, exactly as plan §3.7 spells
  // them. Money is `""` (the organization's currency is the tenant's, not the
  // code's — plan Q8); a per-day count is `""` too.
  energy_cost_per_h: "",
  co2_kg_per_h: "kg/h",
  energy_cost_today: "",
  co2_kg_today: "kg",
  energy_saving_vs_baseline_pct: "%",
  demand_vs_contract_pct: "%",
  tap_changes_per_day: "",
  fuel_hours_remaining_h: "h",
  downtime_h_24h: "h",
  availability_pct_24h: "%",
  starts_per_day: "",
  co2_avoided_kg_today: "kg",
  performance_ratio_pct: "%",
  specific_yield_kwh_kwp_day: "kWh/kWp/day",
  capacity_utilization_pct: "%",
  steps_per_day: "",
  kl_today: "KL",
  water_cost_today: "",
  water_saving_vs_baseline_pct: "%",
  // `E4.1c` PR 2b — `SUSTAINABILITY_MECHANICAL_POINT_KEYS` (5),
  // `SUSTAINABILITY_HVAC_POINT_KEYS` (1), `SUSTAINABILITY_FACILITY_POINT_KEYS`
  // (4), plan §3.7. A count is `""`; hours are `h`.
  duty_hours_pct_24h: "%",
  starts_per_hour: "",
  door_cycles_per_day: "",
  trips_per_day: "",
  out_of_service_hours_month: "h",
  fan_energy_kwh_day: "kWh",
  isolation_hours_month: "h",
  occupied_hours_day: "h",
  fan_hours_day: "h",
  uptime_pct_24h: "%",
  // `E4.2` PR 2 (U6) — fourteen entries: the feeder's six *_this_month /
  // *_this_year rows, solar PV's two, the six water classes' four, and the
  // two executive codes with no stock formula (ADR 0072 decision 4).
  kwh_this_month: "kWh",
  kwh_this_year: "kWh",
  energy_cost_this_month: "",
  energy_cost_this_year: "",
  co2_kg_this_month: "kg",
  co2_kg_this_year: "kg",
  co2_avoided_kg_this_month: "kg",
  co2_avoided_kg_this_year: "kg",
  operational_efficiency_pct: "%",
  kl_this_month: "KL",
  kl_this_year: "KL",
  water_cost_this_month: "",
  water_cost_this_year: "",
  water_recycle_pct: "%",
};
