import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join, relative } from "node:path";

import { describe, expect, it } from "vitest";

import {
  colourFindings,
  colourFunctions,
  darkVariants,
  hexLiterals,
  namedColours,
  paletteClasses,
  roleOpacityModifiers,
  scanColourFiles,
  webColourSourceFiles,
} from "./support/colour-scan";
import { parseTokenBlocks } from "./support/colour-tokens";
import { repoRoot } from "./support/source-scan";

/**
 * `F3.65` — the colour-roles ratchet gate (ADR 0078, plan `docs/plans/f3.65a-colour-tokens.md`
 * §2.5, D4). `apps/web` colours through role tokens (`bg-surface`, `text-ink-muted`,
 * `border-critical-line`); a stock Tailwind palette class, a `bms-*` class, a hex literal or a
 * colour-function literal (`rgb()`, `hsl()`, `oklch()`, `color-mix()` …) is a colour that no
 * theme can move.
 *
 * **The rule.** Scanned: `apps/web/src/**\/*.{ts,tsx,css}` minus `*.spec.*`, `*.test.*` and
 * `test-setup.ts`, comments blanked (`tests/support/colour-scan.ts`).
 *  - `palette`, `hex` and `func` are counted per file against `FLOOR`, an exact table compared in
 *    both directions (D4): a total would let one file rise while another falls.
 *  - six kinds have no table; every occurrence is a `file:line` finding (OQ7 and the review of
 *    this row) — a `dark:` variant (R12), an arbitrary variant on `data-theme` (R12b), a CSS named
 *    colour (R14), `prefers-color-scheme` (R15) and `matchMedia(` (R16), both also in
 *    `apps/web/index.html` with its `<!-- -->` comments blanked, and `text-on-dark` in one class
 *    string with an opaque `bg-accent` / `bg-accent-strong` (R17; a variant prefix counts, a `/NN`
 *    fill does not). R18 fails a finding whose label no case filters for.
 *
 * **The review rule for `FLOOR`.** A number may only fall, and a row may only disappear. A diff
 * that raises a number or adds a row is a new hard-coded colour and is refused in review; the
 * migrating commit lowers its own row (`F3.65a` U7 and U8 did so for `app-shell.tsx` and
 * `login-page.tsx`; `F3.65b` did so for every other file). Since `F3.65b` **palette is a hard
 * zero** (R20): every row reads `palette: 0`, and a palette class fails by file. `F3.65c` brings
 * hex and func to zero, deletes the table, and removes the stock palette and `bms.*` from
 * `tailwind.config.js`.
 *
 * **Measured.** First generated at `7fd51d35` (`F3.65a`): 305 files walked, 141 rows, palette
 * 3,104 · hex 190 · func 2. Re-generated by `F3.65b` after its six directory groups: 305 files
 * walked, 16 rows, palette 0 · hex 188 · func 2 — the 16 files `F3.65c` recolours.
 *
 * **NOT covered — these escape the scan today:**
 *  - a class name built by concatenation or from props (`` `bg-${tone}-600` ``, `className={c}`
 *    where `c` arrives from a caller);
 *  - `style={{ color }}` from a variable, and a colour computed at run time;
 *  - colours outside `apps/web/src`: `tailwind.config.js` (T11 holds its role leaves), `public/`,
 *    and the two mockups `TRINETRA.html` / `ESKOM_SMOC.html`; `apps/web/index.html` is scanned
 *    for the hard-zero kinds only, not counted for palette, hex or func;
 *  - a file under `apps/web/src` that is not `.ts`, `.tsx` or `.css` (none holds a colour today);
 *  - a four-digit `#RGBA` hex literal, `theme(colors.…)` in an arbitrary value, and a named
 *    colour inside a shorthand (`border: 1px solid red`), as a bare CSS value with no `;` after it,
 *    or in an arbitrary class (`text-[red]`);
 *  - `color(display-p3 …)`, and a colour function whose first argument is neither a number nor
 *    `from` (`oklch(var(--x))`, `rgb(none …)`); `color-mix(` counts whatever its arguments;
 *  - a raw CSS rule aimed at the theme in a `.css` file (`[data-theme="dark"] .x { … }`): only a
 *    role declaration outside `index.css`'s two blocks is caught (tokens T14);
 *  - `matchMedia` reached through an alias or a computed key (`window["matchMedia"]`);
 *  - role misuse the R17 string check cannot see: a pair split across the branches of a ternary,
 *    across props, or between a parent and a child; `text-on-dark` on any other light fill; and a
 *    logo plate written `bg-surface` rather than `bg-on-dark` (it turns dark in the dark theme);
 *  - third-party CSS imported from `node_modules` (Leaflet's own `leaflet.css`, whose popup
 *    `background: white` `index.css` overrides by hand) — `node_modules` is never walked;
 *  - Tailwind preflight's own defaults other than the border and ring-offset colours that
 *    `tailwind.config.js` sets (for example the input placeholder colour, stock `gray-400`) — the
 *    generated CSS is not scanned.
 *
 * **Known over-counts** (a finding with no colour; they fail loud, never silent): a fragment
 * such as `#bad-id` or `#add` reads as hex, because only a following hex digit ends a match; a
 * comment that contains `<button` is not blanked (`blankComments` keeps it for `F4.164`).
 */

describe("F3.65 colour scan — fixtures", () => {
  it("R1a a palette class is found once", () => {
    expect(paletteClasses('<div className="p-2 bg-red-600 rounded" />')).toEqual(["bg-red-600"]);
  });

  it("R1b variants are stripped and every colour utility prefix counts", () => {
    const src =
      '"hover:bg-sky-500 focus:ring-offset-white shadow-black/20 border-l-red-600 after:bg-red-600 to-amber-300/50 stroke-gray-400"';
    expect(paletteClasses(src)).toEqual([
      "bg-sky-500",
      "ring-offset-white",
      "shadow-black/20",
      "border-l-red-600",
      "bg-red-600",
      "to-amber-300/50",
      "stroke-gray-400",
    ]);
  });

  it("R1c bms-green-dark matches whole, not as bms-green", () => {
    expect(paletteClasses('"hover:bg-bms-green-dark text-bms-green"')).toEqual([
      "bg-bms-green-dark",
      "text-bms-green",
    ]);
  });

  it("R1d an arbitrary opacity modifier stays part of the class", () => {
    expect(paletteClasses('"bg-white/[.06]"')).toEqual(["bg-white/[.06]"]);
  });

  it("R2a a six-digit hex literal is found once", () => {
    expect(hexLiterals('<path stroke="#DC2626" />')).toEqual(["#DC2626"]);
  });

  it("R2b three- and eight-digit hex literals count", () => {
    expect(hexLiterals('const a = "#fff"; const b = "#00000080";')).toEqual(["#fff", "#00000080"]);
  });

  it("R3a an rgba() literal is found once", () => {
    expect(colourFunctions('ctx.fillStyle = "rgba(0, 0, 0, 0.5)";')).toEqual(["rgba("]);
  });

  it("R3b a colour function after _, ( or , counts (arbitrary-value classes)", () => {
    const src = '"shadow-[0_0_0_1px_rgba(0,0,0,.1)] bg-[linear-gradient(hsl(0_0%_0%),rgb(1_2_3))]"';
    expect(colourFunctions(src)).toEqual(["rgba(", "hsl(", "rgb("]);
  });

  it("R4a a dark: variant is found once, also behind another variant", () => {
    expect(darkVariants('"p-2 md:dark:bg-slate-900"')).toEqual(["dark:"]);
  });

  it("R4b text-on-dark/70, --on-dark: and a { dark: … } object key are not dark: variants", () => {
    const src = '"text-on-dark/70 hover:text-on-dark"\n  --on-dark: 255 255 255;\nconst t = { dark: 1, light: 0 };';
    expect(darkVariants(src)).toEqual([]);
  });

  it("R4c a named colour in an SVG attribute, a style object and a CSS declaration counts", () => {
    const src = '<rect fill="white" />\n<p style={{ color: "red" }} />\n.x { background-color: Navy; }';
    expect(namedColours(src)).toEqual(["white", "red", "Navy"]);
  });

  it("R4d bg-white, currentColor, none, transparent, a tone key and a constant are not named colours", () => {
    const src =
      '<rect className="bg-white" fill="currentColor" stroke="none" />\n<p style={{ color: "transparent" }} />\nconst t = { tone: "red" };\n<line stroke={GREEN} />';
    expect(namedColours(src)).toEqual([]);
  });

  it("R3c oklch(, oklab(, lab(, lch(, hwb( and color-mix( are colour functions", () => {
    const src = '"oklch(70% 0.1 200) oklab(0.5 0 0) lab(50% 1 2) lch(50 1 2) hwb(120 30% 20%) color-mix(in srgb, red, blue)"';
    expect(colourFunctions(src)).toEqual(["oklch(", "oklab(", "lab(", "lch(", "hwb(", "color-mix("]);
  });

  it("R3d collab( (lab( after a letter) and oklch(var(--x)) are not colour functions; oklch(0.5 …) counts once", () => {
    expect(colourFunctions("collab(1); const c = 'oklch(0.5 0.1 20)'; const v = 'oklch(var(--x))';")).toEqual(["oklch("]);
  });

  it("R4e an arbitrary variant on data-theme is a theme-variant finding", () => {
    expect(colourFindings('"[[data-theme=dark]_&]:bg-surface"', "f.tsx")).toEqual([
      "f.tsx:1 theme variant [[data-theme=dark]_&]:",
    ]);
  });

  it("R4f data-[theme=dark]:, group-[[data-theme=dark]_&]: and [html[data-theme=dark]_&]: are each a theme-variant finding", () => {
    const src = '"data-[theme=dark]:bg-x group-[[data-theme=dark]_&]:bg-x [html[data-theme=dark]_&]:bg-x"';
    expect(colourFindings(src, "f.tsx").filter((f) => f.includes(" theme variant "))).toHaveLength(3);
  });

  it("R4g an @media (prefers-color-scheme) block is a finding", () => {
    expect(colourFindings("@media (prefers-color-scheme: dark) {\n}\n", "f.css")).toEqual([
      "f.css:1 prefers-color-scheme",
    ]);
  });

  it("R4h a matchMedia( call is a finding", () => {
    expect(colourFindings('const q = window.matchMedia("(min-width: 640px)");', "f.ts")).toEqual(["f.ts:1 matchMedia("]);
  });

  it("R4i prefers-color-scheme inside an HTML comment of an .html file is not a finding", () => {
    expect(colourFindings("<!--\n  No prefers-color-scheme here.\n-->\n<div></div>", "f.html")).toEqual([]);
  });

  it("R4j text-on-dark in one class string with an opaque bg-accent is a finding, named by line", () => {
    const src = 'const a = 1;\n<button className="rounded bg-accent py-3 text-on-dark" />';
    expect(colourFindings(src, "f.tsx")).toEqual(["f.tsx:2 text-on-dark on an opaque accent fill bg-accent"]);
  });

  it("R4k hover:bg-accent-strong with text-on-dark/70 in one template literal is a finding", () => {
    const src = "const c = `px-2 ${x} hover:bg-accent-strong text-on-dark/70`;";
    expect(colourFindings(src, "f.tsx")).toEqual(["f.tsx:1 text-on-dark on an opaque accent fill hover:bg-accent-strong"]);
  });

  it("R4l text-on-dark beside a translucent bg-accent/10, and text-on-accent on bg-accent, are not findings", () => {
    const src = '<a className="bg-accent/10 text-on-dark" /><b className="bg-accent text-on-accent" />';
    expect(colourFindings(src, "f.tsx")).toEqual([]);
  });

  it("R4m the two branches of a ternary are separate class strings", () => {
    const src = 'const c = `px-2 ${active ? "p-1 bg-accent text-on-accent p-1" : "p-1 text-on-dark p-1"}`;';
    expect(colourFindings(src, "f.tsx")).toEqual([]);
  });

  it("R4n roleOpacityModifiers reads the modifier of a role class, variant or not, and skips a palette class", () => {
    const src = '"text-on-dark/72 hover:bg-accent/[.06] bg-surface text-white/58 border-line-strong/40"';
    expect(roleOpacityModifiers(src, ["on-dark", "accent", "surface", "line", "line-strong"]).map((m) => m.className)).toEqual([
      "text-on-dark/72",
      "bg-accent/[.06]",
      "border-line-strong/40",
    ]);
  });

  it("R5 #0b1a2f_0% in an arbitrary-value class counts as hex", () => {
    expect(hexLiterals('"bg-[linear-gradient(135deg,#0b1a2f_0%,#05351f_100%)]"')).toEqual([
      "#0b1a2f",
      "#05351f",
    ]);
  });

  it("R6 #root and &#123; are not hex literals", () => {
    expect(hexLiterals('document.querySelector("#root"); const s = "&#123;";')).toEqual([]);
  });

  it("R7 rgb(var(--x) / <alpha-value>) is not a colour function", () => {
    expect(colourFunctions('canvas: "rgb(var(--canvas) / <alpha-value>)",')).toEqual([]);
  });

  it("R8a a palette class in a // comment is not counted", () => {
    expect(paletteClasses('// was bg-red-600\nconst c = "p-2";')).toEqual([]);
  });

  it("R8b a palette class, hex and rgb() in a /* */ comment are not counted", () => {
    const src = '/* bg-red-600 #DC2626 rgb(1, 2, 3) */\n.x { --a: 1 2 3; }';
    expect([...paletteClasses(src), ...hexLiterals(src), ...colourFunctions(src)]).toEqual([]);
  });

  it("R9a role classes are not palette classes", () => {
    expect(
      paletteClasses('"bg-surface text-ink-muted border-critical-line text-on-dark/70 bg-neutral-ink"'),
    ).toEqual([]);
  });

  it("R9b no role in index.css, under any prefix or opacity, reads as a palette class", () => {
    const { light } = parseTokenBlocks(readFileSync(join(repoRoot, "apps/web/src/index.css"), "utf8"));
    const classes = [...light.keys()].flatMap((role) =>
      ["bg", "text", "border", "ring", "hover:bg"].flatMap((p) => [`${p}-${role}`, `${p}-${role}/70`]),
    );
    expect(paletteClasses(`"${classes.join(" ")}"`)).toEqual([]);
  });

  it("R10a text-white/70 counts once", () => {
    expect(paletteClasses('"text-white/70"')).toEqual(["text-white/70"]);
  });

  it("R10b a file that cannot be read throws rather than being skipped", () => {
    const missing = join(repoRoot, "apps/web/src/no-such-file-f3-65.tsx");
    expect(() => scanColourFiles([missing])).toThrow(/ENOENT/);
  });
});

/**
 * The per-file floor, exact (D4). Paths are relative to `apps/web/src/`. Review rule: a number
 * may only fall, a row may only disappear (see the file docblock). Every palette cell is 0 since
 * `F3.65b` (R20 holds it); `F3.65c` empties the table.
 */
const FLOOR: { file: string; palette: number; hex: number; func: number }[] = [

];

function floorDiff(): string[] {
  const scanned = new Map(scanColourFiles(webColourSourceFiles()).rows.map((r) => [r.file, r]));
  const floor = new Map(FLOOR.map((r) => [`apps/web/src/${r.file}`, r]));
  const out: string[] = [];
  for (const [file, s] of scanned) {
    const f = floor.get(file);
    if (!f) {
      out.push(`${file}: palette ${s.palette}, hex ${s.hex}, func ${s.func} (no FLOOR row)`);
      continue;
    }
    for (const kind of ["palette", "hex", "func"] as const) {
      if (s[kind] !== f[kind]) out.push(`${file}: ${kind} ${s[kind]} (floor ${f[kind]})`);
    }
  }
  for (const file of floor.keys()) {
    if (!scanned.has(file)) out.push(`${file}: in FLOOR but has no colour finding (delete the row)`);
  }
  return out.sort();
}

const INDEX_HTML = join(repoRoot, "apps/web/index.html");

/** Tailwind's default `theme.opacity` scale, from the installed package (a dependency of `apps/web`). */
const defaultOpacity = (
  createRequire(join(repoRoot, "apps/web/package.json"))("tailwindcss/defaultTheme") as { opacity: Record<string, string> }
).opacity;

/** The hard-zero findings of every web source file plus `apps/web/index.html` (its HTML comments blanked). */
function treeAndHtmlFindings(): string[] {
  return [
    ...scanColourFiles(webColourSourceFiles()).findings,
    ...colourFindings(readFileSync(INDEX_HTML, "utf8"), "apps/web/index.html"),
  ];
}

describe("F3.65 colour-roles gate — the tree", () => {
  it("R11 every file's palette, hex and func count equals its FLOOR row, both directions", () => {
    expect(floorDiff()).toEqual([]);
  });

  it("R12 no file uses a dark: variant", () => {
    const findings = scanColourFiles(webColourSourceFiles()).findings.filter((f) => f.endsWith(" dark: variant"));
    expect(findings).toEqual([]);
  });

  it("R12b no file uses an arbitrary variant that targets data-theme", () => {
    const findings = scanColourFiles(webColourSourceFiles()).findings.filter((f) => / theme variant /.test(f));
    expect(findings).toEqual([]);
  });

  it("R13 at least 300 files were walked", () => {
    expect(scanColourFiles(webColourSourceFiles()).walked).toBeGreaterThanOrEqual(300);
  });

  it("R14 no file uses a named colour as a colour value", () => {
    const findings = scanColourFiles(webColourSourceFiles()).findings.filter((f) => / named colour /.test(f));
    expect(findings).toEqual([]);
  });

  it("R15 no web source file and not index.html mentions prefers-color-scheme (ADR 0078 decision 4)", () => {
    expect(treeAndHtmlFindings().filter((f) => f.endsWith(" prefers-color-scheme"))).toEqual([]);
  });

  it("R16 no web source file and not index.html calls matchMedia(", () => {
    expect(treeAndHtmlFindings().filter((f) => f.endsWith(" matchMedia("))).toEqual([]);
  });

  it("R17 no class string puts text-on-dark on an opaque bg-accent or bg-accent-strong", () => {
    expect(treeAndHtmlFindings().filter((f) => / text-on-dark on an opaque accent fill /.test(f))).toEqual([]);
  });

  // Owner ruling 2026-09-28: `text-on-dark/72` and `/58` emitted no CSS (Tailwind 3 has no 72 or 58
  // opacity step), so the login hero text showed full white. The scale is Tailwind's own.
  it("R19 every opacity modifier on a role class is a Tailwind default opacity step or an arbitrary /[…] value", () => {
    const steps = new Set(Object.keys(defaultOpacity));
    const roles = [...parseTokenBlocks(readFileSync(join(repoRoot, "apps/web/src/index.css"), "utf8")).light.keys()];
    const offScale: string[] = [];
    for (const full of webColourSourceFiles()) {
      const src = readFileSync(full, "utf8");
      const file = relative(repoRoot, full).split("\\").join("/");
      for (const { index, className, modifier } of roleOpacityModifiers(src, roles)) {
        if (steps.has(modifier) || /^\[[^\]]+\]$/.test(modifier)) continue;
        offScale.push(`${file}:${src.slice(0, index).split("\n").length} ${className}`);
      }
    }
    expect(offScale).toEqual([]);
  });

  // `F3.65b` (plan `docs/plans/f3.65b-pages-on-roles.md` OQ5): the tree reached palette 0, so a
  // palette class is a hard zero from here, named by file whatever `FLOOR` says.
  it("R20 no file uses a stock palette or bms-* colour class", () => {
    const rows = scanColourFiles(webColourSourceFiles()).rows.filter((r) => r.palette > 0);
    expect(rows.map((r) => `${r.file}: palette ${r.palette}`)).toEqual([]);
  });

  it("R18 every hard-zero finding carries a label a case above filters for", () => {
    const known =
      /^\S+:\d+ (?:dark: variant|named colour \S+|theme variant \S+|prefers-color-scheme|matchMedia\(|text-on-dark on an opaque accent fill \S+)$/;
    expect(treeAndHtmlFindings().filter((f) => !known.test(f))).toEqual([]);
  });
});
