import type { AutomationRuleOperator } from "@bms/shared";

/**
 * ADR 0050 decision 2's in-range predicate, expressed as SQL rather than
 * TypeScript, so the roll-up job (a later `E1.3` unit) can push `fires(...)`
 * into the query that scans `telemetry.point_values*`. `compare()` in
 * `../rules/rule-evaluation.ts` is this module's TypeScript twin over the
 * same closed operator vocabulary; the two must never drift, which is why
 * both are exhaustive over `AutomationRuleOperator` rather than each hand-
 * listing the five operators separately.
 */

/**
 * Closed map from `AutomationRuleOperator` to its SQL comparison symbol.
 *
 * Typed as `Record<AutomationRuleOperator, string>` on purpose: if the shared
 * vocabulary (`packages/shared/src/contracts/operations.ts`) ever gains a
 * sixth operator, this object literal stops satisfying the type and the
 * build fails here — the alternative (an untyped map) would let a new
 * operator fall through `firesCaseSql` silently as an always-NULL `WHEN` that
 * is never generated at all.
 */
export const SQL_COMPARATOR: Record<AutomationRuleOperator, string> = {
  gt: ">",
  gte: ">=",
  lt: "<",
  lte: "<=",
  eq: "=",
};

/**
 * A defence-in-depth guard on a non-user-facing seam, not input validation:
 * `firesCaseSql`'s three arguments are column expressions the *caller*
 * supplies (a later unit's own SQL fragments, e.g. `pv.value` or
 * `r.threshold_value`), never end-user input. The function nonetheless
 * builds SQL by string concatenation, so a bare identifier check is cheap
 * insurance against a future caller wiring in something unexpected, and a
 * security reviewer will look here first.
 */
const IDENTIFIER_EXPR = /^[a-z_][a-z0-9_]*(\.[a-z_][a-z0-9_]*)?$/;

function assertIdentifierExpr(argumentName: string, value: string): void {
  if (!IDENTIFIER_EXPR.test(value)) {
    throw new Error(
      `${argumentName} must be a bare or singly-qualified lowercase identifier, got ${JSON.stringify(value)}`,
    );
  }
}

/**
 * Builds the `CASE` expression that decides `fires(operator, value,
 * threshold)` for one sample, over the SQL text supplied for each operand.
 *
 * The `WHEN` arms are generated by iterating `SQL_COMPARATOR` — never
 * hand-written — so the map and the SQL it produces cannot drift apart.
 *
 * There is deliberately **no `ELSE` branch**. If `operatorExpr` reads a value
 * outside the closed vocabulary, or either `operatorExpr` or `thresholdExpr`
 * is `NULL` (a threshold rule with a NULL `operator`/`threshold_value` is
 * valid per `packages/db/src/schema/bms-schema.ts`), the `CASE` evaluates to
 * SQL `NULL` rather than `false`. That `NULL` is exactly ADR 0050 Amendment 1
 * decision 7's "skipped" signal, not "did not fire". An `ELSE false` would
 * make an unevaluatable rule read as "did not fire", which makes the sample
 * look in-range and inflates the health score — the same defect ADR 0050
 * decision 3 exists to prevent, reached by a different road. Do not add one.
 */
export function firesCaseSql(valueExpr: string, operatorExpr: string, thresholdExpr: string): string {
  assertIdentifierExpr("valueExpr", valueExpr);
  assertIdentifierExpr("operatorExpr", operatorExpr);
  assertIdentifierExpr("thresholdExpr", thresholdExpr);

  const whenArms = Object.entries(SQL_COMPARATOR)
    .map(([operator, symbol]) => `  WHEN '${operator}' THEN ${valueExpr} ${symbol} ${thresholdExpr}`)
    .join("\n");

  return `CASE ${operatorExpr}\n${whenArms}\nEND`;
}
