import { z } from "zod";

import { metricCatalogKeySchema, rollupCoverageSchema } from "./dashboard-builder";

/**
 * One cell of a resolved dataset row.
 *
 * **A closed union, never `z.unknown()`.** §4.8 records what that costs and that this repo has
 * already paid it: `z.unknown()` produces an *optional* key, and `z.any()` and
 * `z.custom<unknown>()` behave identically — "do not spend an afternoon on it". Four types is
 * what a SQL projection can actually return once a timestamp is serialised, so naming them is
 * both stricter and cheaper.
 */
const datasetCellSchema = z.union([z.string(), z.number(), z.boolean(), z.null()]);

/**
 * A resolved catalog value, as `GET /api/v1/metric-catalog/:key` returns it (`F3.35` Stage C).
 *
 * `z.discriminatedUnion` on `shape`, so a mislabelled payload fails rather than narrowing into
 * the wrong arm and rendering an empty table. Two plain `z.object` arms — no `.merge()`, no
 * `.omit().extend()`, which ADR 0030 Amendment 1 bans inside `contracts/` because a flattened
 * schema still typechecks and only a source scan catches it.
 *
 * **`value` is nullable on the metric arm, deliberately.** An entry can legitimately resolve to
 * nothing: `E1.3` returns a null mean score when no tag carries a published threshold rule, and
 * `F4.69` is the open row for the seed gap that makes that the current state. Rendering a null
 * as `0` would put a fabricated number in front of an operator, which is the one failure this
 * contract must make impossible.
 *
 * **`truncated` is a field rather than an inference.** A caller cannot tell a dataset that has
 * exactly `MAX_DATASET_ROWS` rows from one that was cut off at it, and the difference decides
 * whether the card is showing the whole answer.
 *
 * **`coverage` and `currency` are optional on the metric arm, deliberately** (`E4.2`, ADR 0072
 * decision 2). The arm is shared by every metric entry; `sustainability.total` emits both, the
 * three older emitters emit neither and do not change. A required field here would make
 * `checkResponse` throw on every existing dashboard in dev and test (ADR 0030). The dataset arm
 * carries coverage as a column (`"fresh/carrying"`), not a field — a cell is a scalar.
 */
export const metricCatalogValueDtoSchema = z.discriminatedUnion("shape", [
  z.object({
    shape: z.literal("metric"),
    key: metricCatalogKeySchema,
    value: z.number().nullable(),
    unit: z.string().nullable(),
    coverage: rollupCoverageSchema.optional(),
    currency: z.string().nullable().optional(),
  }),
  z.object({
    shape: z.literal("dataset"),
    key: metricCatalogKeySchema,
    columns: z.array(z.string()),
    rows: z.array(z.record(datasetCellSchema)),
    truncated: z.boolean(),
  }),
]);

/**
 * `GET /dashboards/:id/catalog-values` — every catalog binding on one dashboard, resolved.
 *
 * **Keyed by `sourceId`, and one request per dashboard rather than one per entry.** The viewer
 * holds one socket per page (ADR 0048's Consequences), and a per-entry route would be N round
 * trips for a page that already knows all N bindings from its own read.
 *
 * **The route lives on `/dashboards` because scope does.** A dashboard may be scoped to a
 * location or an asset group, and every entry has to be narrowed to it — a site dashboard whose
 * tile reads `alarms.active.count` must show the site's count, not the organization's. That
 * narrowing needs the dashboard row, which a `/metric-catalog/:key` route could never see. ADR
 * 0048 decision 3's "one new endpoint on `@Controller("telemetry")`" is the POINT-AGGREGATE
 * endpoint, shipped in Stage A; do not let that sentence pull this one onto that controller.
 *
 * A binding whose widget was deleted between the dashboard read and this call simply does not
 * appear. The viewer renders "no value" for a `sourceId` it does not get back, which is the same
 * state ADR 0047 decision 3 requires for a widget whose point bindings have cascaded to zero.
 */
export const dashboardCatalogValueDtoSchema = z.object({
  /**
   * The binding's own row id. Present because it is the truth about which row answered, and
   * **deliberately not what a viewer keys on** — see `widgetId`.
   */
  sourceId: z.string().uuid(),
  /**
   * The NATURAL key, and the pair a viewer must match on (correctness review, Medium).
   *
   * **`sourceId` is regenerated by every widget save.** `putWidgets` replaces a widget's
   * bindings rather than editing them — `DELETE` by `widget_id` then re-`INSERT` — and
   * `dashboard_widget_sources.id` is `defaultRandom()`, so renaming a tile mints a new
   * `sourceId` for an unchanged binding. The viewer holds two queries that refresh on
   * different schedules: the catalog read polls every minute, the dashboard read does not poll
   * at all. On a wall display that never receives focus, the catalog answers with new
   * `sourceId`s while the page still holds the old ones, and every tile silently falls to "no
   * value" — `status: "ready"`, `stale: false`, a confident wrong answer.
   *
   * `(widgetId, catalogKey)` survives that, because `putWidgets` preserves a widget's `id`
   * across a replace and `dashboard_widget_sources_widget_key_key` makes the key unique per
   * widget. It is the same property the point path already relies on: `pointRef` is
   * `assetId:pointKey`, a natural key, which is why that path was never exposed to this.
   */
  widgetId: z.string().uuid(),
  catalogKey: metricCatalogKeySchema,
  resolved: metricCatalogValueDtoSchema,
});

export const dashboardCatalogValuesResponseSchema = z.object({
  values: z.array(dashboardCatalogValueDtoSchema),
  /** When the resolve ran, so a viewer can show staleness without a second clock. */
  resolvedAt: z.string().datetime(),
});
