#!/usr/bin/env bash
# ADR 0096 — one-time (and re-runnable) bootstrap of the AWS demo host.
#
# Run as root from a checkout of this repository:
#   sudo bash deploy/aws/setup-server.sh /path/to/bmsdeploy.pub
#
# Idempotent. Each step leaves an existing result alone:
#   1. a 4 GiB swapfile on the /var/www data disk (the host has no swap)
#   2. the `bmsdeploy` user, its forced-command key and one sudoers rule
#   3. /usr/local/sbin/bms-ctl and bms-ctl-ssh (always reinstalled — this is
#      how an edit to either script reaches the host)
#   4. /var/www/bms/repo, a sparse, blob-less clone of the public repository
#   5. /var/www/bms/.env with generated secrets (never overwritten)
#
# It does not touch Caddy: /etc/caddy/sites/bms.demosites.co.in.caddy is
# edited by hand (see docs/runbooks/aws-demo-deployment.md).

set -euo pipefail

REPO_URL="https://github.com/GhochangFu/EMS.git"
IMAGE_OWNER="ghochangfu"
PUBLIC_HOST="bms.demosites.co.in"
BMS_HOME=/var/www/bms
SWAPFILE=/var/www/swapfile
HERE="$(cd "$(dirname "$0")" && pwd)"

[ "$(id -u)" -eq 0 ] || { echo "run as root" >&2; exit 1; }
PUBKEY_FILE="${1:-}"

# 1. Swap ---------------------------------------------------------------------
if ! swapon --show=NAME --noheadings | grep -qx "$SWAPFILE"; then
  if [ ! -f "$SWAPFILE" ]; then
    fallocate -l 4G "$SWAPFILE"
    chmod 600 "$SWAPFILE"
    mkswap "$SWAPFILE" >/dev/null
  fi
  swapon "$SWAPFILE"
  echo "swap: $SWAPFILE on"
fi
grep -q "^$SWAPFILE " /etc/fstab || echo "$SWAPFILE none swap sw 0 0" >> /etc/fstab
# Swap is the safety margin, not working memory.
echo "vm.swappiness=10" > /etc/sysctl.d/99-bms-swap.conf
sysctl -q -p /etc/sysctl.d/99-bms-swap.conf

# 2. Deploy user ----------------------------------------------------------------
if ! id bmsdeploy >/dev/null 2>&1; then
  useradd --system --create-home --shell /bin/sh bmsdeploy
  passwd -l bmsdeploy >/dev/null
fi
if [ -n "$PUBKEY_FILE" ]; then
  key="$(head -n 1 "$PUBKEY_FILE")"
  case "$key" in ssh-ed25519\ *) ;; *) echo "expected an ssh-ed25519 public key" >&2; exit 1 ;; esac
  install -d -m 0700 -o bmsdeploy -g bmsdeploy ~bmsdeploy/.ssh
  printf 'command="/usr/local/sbin/bms-ctl-ssh",restrict %s\n' "$key" > ~bmsdeploy/.ssh/authorized_keys
  chown bmsdeploy:bmsdeploy ~bmsdeploy/.ssh/authorized_keys
  chmod 0600 ~bmsdeploy/.ssh/authorized_keys
fi
sudoers=/etc/sudoers.d/bms-deploy
printf 'bmsdeploy ALL=(root) NOPASSWD: /usr/local/sbin/bms-ctl\n' > "$sudoers.tmp"
visudo -cqf "$sudoers.tmp"
install -m 0440 "$sudoers.tmp" "$sudoers"
rm -f "$sudoers.tmp"

# 3. Control scripts --------------------------------------------------------------
install -m 0755 -o root -g root "$HERE/bms-ctl.sh" /usr/local/sbin/bms-ctl
install -m 0755 -o root -g root "$HERE/bms-ctl-ssh.sh" /usr/local/sbin/bms-ctl-ssh

# 4. Repository checkout (only what the host reads) ---------------------------------
install -d -m 0750 "$BMS_HOME"
if [ ! -d "$BMS_HOME/repo/.git" ]; then
  git clone --quiet --filter=blob:none --no-checkout "$REPO_URL" "$BMS_HOME/repo"
  git -C "$BMS_HOME/repo" sparse-checkout set deploy/aws infra/keycloak packages/db/docker-init
  git -C "$BMS_HOME/repo" checkout --quiet --detach origin/main
fi

# 5. Secrets ------------------------------------------------------------------------
if [ ! -f "$BMS_HOME/.env" ]; then
  hex() { openssl rand -hex "$1"; }
  umask 077
  cat > "$BMS_HOME/.env" <<EOF
# Generated by deploy/aws/setup-server.sh on $(date -u +%Y-%m-%dT%H:%MZ). Never commit.
PUBLIC_HOST=$PUBLIC_HOST
IMAGE_OWNER=$IMAGE_OWNER
POSTGRES_PASSWORD=$(hex 24)
BMS_OWNER_PASSWORD=$(hex 24)
BMS_TENANT_PASSWORD=$(hex 24)
BMS_FLEET_PASSWORD=$(hex 24)
BMS_AUTH_PASSWORD=$(hex 24)
JWT_SECRET=$(hex 48)
KEYCLOAK_ADMIN_PASSWORD=$(hex 24)
KEYCLOAK_ADMIN_CLIENT_SECRET=$(hex 32)
MINIO_ROOT_USER=bms_minio
MINIO_ROOT_PASSWORD=$(hex 24)
CREDENTIAL_ENCRYPTION_KEY=$(openssl rand -base64 32)
# Password of every seeded demo login (admin@bms.local, operator@bms.local, ...).
DEMO_PASSWORD=Nexus-$(hex 6)
# The ingest host's fallback broker login (ADR 0096 Amendment 1). Set by hand;
# `bms-ctl ingest start` refuses to start while either is empty.
MQTT_USERNAME=
MQTT_PASSWORD=
# Optional: the onboarding agent's model provider (ADR 0090).
LLM_PROVIDER=
OPENAI_API_KEY=
OPENAI_MODEL=
OPENROUTER_API_KEY=
OPENROUTER_MODEL=
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=
EOF
  echo ".env: generated $BMS_HOME/.env"
fi
chmod 0600 "$BMS_HOME/.env"

echo "setup-server: done"
