-- F3.32f / ADR 0086 decision 9 — the third-party symbol libraries: QElectroTech (qet), Wikimedia
-- Commons P&ID (wmpid) and draw.io (drawio).
--
-- 1. THREE LIBRARY ROWS in `bms.mimic_symbol_libraries`, exactly the registry's entries 5–7 in
--    `packages/shared/src/mimic-symbol-libraries/index.ts` (sort_order 50, 60, 70; stroke style).
--
-- 2. THE SYMBOL ROWS, 137 qet + 157 wmpid + 131 drawio. GENERATED ROWS, pasted from
--      node scripts/mimic-symbols/generate.mjs --qet <dir> --sql-rows qet
--      node scripts/mimic-symbols/generate.mjs --wmpid <dir> --sql-rows wmpid
--      node scripts/mimic-symbols/generate.mjs --drawio <dir> --sql-rows drawio
--    (the directories are the ones `scripts/mimic-symbols/fetch-sources.mjs` writes), then frozen
--    like every committed migration: a later curation change is a new migration. The rows are the
--    generated keys, labels and groups in curation order, sort_order = 10 × position within the
--    library. `tests/f3.32e-mimic-symbol-libraries.test.ts` compares them with the shared and the
--    web generated modules, both ways. Bare ON CONFLICT DO NOTHING (no arbiter), for the
--    0030/0034/0051 reason.
--
-- WHO RUNS WHAT. Both INSERTs run inside `SET ROLE bms_owner`, the role that owns both tables
-- (`0090`), so `0041`'s default privileges and `0090`'s tenant revoke already cover the new rows:
-- privileges are per table, not per row. Neither table has row security, so no tenant GUC is
-- needed. Nothing in this file changes a table, a privilege or a policy. The `DO $$` block
-- asserts the effect, per the 0059/0085/0090 idiom, so a silent ON CONFLICT no-op cannot pass as
-- success.

SET ROLE bms_owner;

INSERT INTO bms.mimic_symbol_libraries (code, label, source, version, licence, attribution_url, style, sort_order) VALUES
  ('qet', 'QElectroTech', 'qelectrotech/qelectrotech-elements', '0.100', 'CC BY 3.0', 'https://qelectrotech.org/wiki/doc/elements_license', 'stroke', 50),
  ('wmpid', 'Wikimedia Commons P&ID', 'Wikimedia Commons Category:P&ID symbols', '2026-09-29', 'Public domain / CC0', 'https://commons.wikimedia.org/wiki/Category:P%26ID_symbols', 'stroke', 60),
  ('drawio', 'draw.io', 'jgraph/drawio stencils (pid, electrical)', '29.3.2', 'CC BY 4.0', 'https://github.com/jgraph/drawio/tree/48b181339578e11da7052ebf5b1fba8499418b77/src/main/webapp/stencils', 'stroke', 70)
ON CONFLICT DO NOTHING;

INSERT INTO bms.mimic_symbols (key, library_code, label, group_code, sort_order) VALUES
  ('qet:open-tank', 'qet', 'Open tank', 'water', 10),
  ('qet:hydraulic-accumulator', 'qet', 'Hydraulic accumulator', 'water', 20),
  ('qet:filter', 'qet', 'Filter', 'water', 30),
  ('qet:storage-tank', 'qet', 'Storage tank', 'water', 40),
  ('qet:horizontal-tank', 'qet', 'Horizontal tank', 'water', 50),
  ('qet:coil-storage-tank', 'qet', 'Coil storage tank', 'water', 60),
  ('qet:horizontal-hot-water-cylinder', 'qet', 'Horizontal hot water cylinder', 'water', 70),
  ('qet:circulating-pump', 'qet', 'Circulating pump', 'water', 80),
  ('qet:flanged-circulating-pump', 'qet', 'Flanged circulating pump', 'water', 90),
  ('qet:vertical-water-pump', 'qet', 'Vertical water pump', 'water', 100),
  ('qet:submersible-pump', 'qet', 'Submersible pump', 'water', 110),
  ('qet:borehole-pump', 'qet', 'Borehole pump', 'water', 120),
  ('qet:horizontal-pump', 'qet', 'Horizontal pump', 'water', 130),
  ('qet:sanitary-circulator', 'qet', 'Sanitary circulator', 'water', 140),
  ('qet:pump-with-check-valve', 'qet', 'Pump with check valve', 'water', 150),
  ('qet:vertical-multistage-pump', 'qet', 'Vertical multistage pump', 'water', 160),
  ('qet:chlorine-dosing-pump', 'qet', 'Chlorine dosing pump', 'water', 170),
  ('qet:cartridge-filter', 'qet', 'Cartridge filter', 'water', 180),
  ('qet:water-softener', 'qet', 'Water softener', 'water', 190),
  ('qet:bladder-tank', 'qet', 'Bladder tank', 'water', 200),
  ('qet:water-meter', 'qet', 'Water meter', 'water', 210),
  ('qet:float-valve', 'qet', 'Float valve', 'water', 220),
  ('qet:foot-valve', 'qet', 'Foot valve', 'water', 230),
  ('qet:backflow-preventer', 'qet', 'Backflow preventer', 'water', 240),
  ('qet:two-way-solenoid-valve', 'qet', 'Two way solenoid valve', 'water', 250),
  ('qet:drain', 'qet', 'Drain', 'water', 260),
  ('qet:panel-radiator', 'qet', 'Panel radiator', 'hvac', 270),
  ('qet:column-radiator', 'qet', 'Column radiator', 'hvac', 280),
  ('qet:ducted-fan-coil', 'qet', 'Ducted fan coil', 'hvac', 290),
  ('qet:unit-heater', 'qet', 'Unit heater', 'hvac', 300),
  ('qet:underfloor-heating', 'qet', 'Underfloor heating', 'hvac', 310),
  ('qet:floor-boiler', 'qet', 'Floor boiler', 'hvac', 320),
  ('qet:wall-boiler', 'qet', 'Wall boiler', 'hvac', 330),
  ('qet:industrial-boiler', 'qet', 'Industrial boiler', 'hvac', 340),
  ('qet:expansion-vessel', 'qet', 'Expansion vessel', 'hvac', 350),
  ('qet:open-expansion-vessel', 'qet', 'Open expansion vessel', 'hvac', 360),
  ('qet:plate-heat-exchanger', 'qet', 'Plate heat exchanger', 'hvac', 370),
  ('qet:tubular-heat-exchanger', 'qet', 'Tubular heat exchanger', 'hvac', 380),
  ('qet:air-heat-exchanger', 'qet', 'Air heat exchanger', 'hvac', 390),
  ('qet:air-to-water-heat-pump', 'qet', 'Air to water heat pump', 'hvac', 400),
  ('qet:split-outdoor-unit', 'qet', 'Split outdoor unit', 'hvac', 410),
  ('qet:split-wall-unit', 'qet', 'Split wall unit', 'hvac', 420),
  ('qet:ceiling-cassette', 'qet', 'Ceiling cassette', 'hvac', 430),
  ('qet:chiller', 'qet', 'Chiller', 'hvac', 440),
  ('qet:vrf-outdoor-unit', 'qet', 'Vrf outdoor unit', 'hvac', 450),
  ('qet:refrigeration-compressor', 'qet', 'Refrigeration compressor', 'hvac', 460),
  ('qet:piston-compressor', 'qet', 'Piston compressor', 'hvac', 470),
  ('qet:scroll-compressor', 'qet', 'Scroll compressor', 'hvac', 480),
  ('qet:screw-compressor', 'qet', 'Screw compressor', 'hvac', 490),
  ('qet:hermetic-compressor', 'qet', 'Hermetic compressor', 'hvac', 500),
  ('qet:condensing-unit', 'qet', 'Condensing unit', 'hvac', 510),
  ('qet:water-cooled-condenser', 'qet', 'Water cooled condenser', 'hvac', 520),
  ('qet:air-cooled-condenser', 'qet', 'Air cooled condenser', 'hvac', 530),
  ('qet:evaporator', 'qet', 'Evaporator', 'hvac', 540),
  ('qet:liquid-receiver', 'qet', 'Liquid receiver', 'hvac', 550),
  ('qet:electronic-expansion-valve', 'qet', 'Electronic expansion valve', 'hvac', 560),
  ('qet:thermostatic-expansion-valve', 'qet', 'Thermostatic expansion valve', 'hvac', 570),
  ('qet:four-way-reversing-valve', 'qet', 'Four way reversing valve', 'hvac', 580),
  ('qet:oil-separator', 'qet', 'Oil separator', 'hvac', 590),
  ('qet:filter-drier', 'qet', 'Filter drier', 'hvac', 600),
  ('qet:cooling-tower', 'qet', 'Cooling tower', 'hvac', 610),
  ('qet:axial-fan', 'qet', 'Axial fan', 'hvac', 620),
  ('qet:centrifugal-fan', 'qet', 'Centrifugal fan', 'hvac', 630),
  ('qet:air-damper', 'qet', 'Air damper', 'hvac', 640),
  ('qet:heating-coil', 'qet', 'Heating coil', 'hvac', 650),
  ('qet:roof-extractor', 'qet', 'Roof extractor', 'hvac', 660),
  ('qet:humidifier', 'qet', 'Humidifier', 'hvac', 670),
  ('qet:fixed-displacement-pump', 'qet', 'Fixed displacement pump', 'mechanical', 680),
  ('qet:variable-displacement-pump', 'qet', 'Variable displacement pump', 'mechanical', 690),
  ('qet:hydraulic-motor', 'qet', 'Hydraulic motor', 'mechanical', 700),
  ('qet:double-acting-cylinder', 'qet', 'Double acting cylinder', 'mechanical', 710),
  ('qet:spring-return-cylinder', 'qet', 'Spring return cylinder', 'mechanical', 720),
  ('qet:water-oil-exchanger', 'qet', 'Water oil exchanger', 'mechanical', 730),
  ('qet:air-compressor', 'qet', 'Air compressor', 'mechanical', 740),
  ('qet:air-receiver', 'qet', 'Air receiver', 'mechanical', 750),
  ('qet:air-dryer', 'qet', 'Air dryer', 'mechanical', 760),
  ('qet:compressed-air-filter', 'qet', 'Compressed air filter', 'mechanical', 770),
  ('qet:air-lubricator', 'qet', 'Air lubricator', 'mechanical', 780),
  ('qet:automatic-water-separator', 'qet', 'Automatic water separator', 'mechanical', 790),
  ('qet:compressed-air-cooler', 'qet', 'Compressed air cooler', 'mechanical', 800),
  ('qet:air-service-unit', 'qet', 'Air service unit', 'mechanical', 810),
  ('qet:vacuum-pump', 'qet', 'Vacuum pump', 'mechanical', 820),
  ('qet:vacuum-generator', 'qet', 'Vacuum generator', 'mechanical', 830),
  ('qet:pneumatic-silencer', 'qet', 'Pneumatic silencer', 'mechanical', 840),
  ('qet:quick-exhaust-valve', 'qet', 'Quick exhaust valve', 'mechanical', 850),
  ('qet:rotary-actuator', 'qet', 'Rotary actuator', 'mechanical', 860),
  ('qet:air-motor', 'qet', 'Air motor', 'mechanical', 870),
  ('qet:pneumatic-spring-cylinder', 'qet', 'Pneumatic spring cylinder', 'mechanical', 880),
  ('qet:pneumatic-double-acting-cylinder', 'qet', 'Pneumatic double acting cylinder', 'mechanical', 890),
  ('qet:check-valve', 'qet', 'Check valve', 'general', 900),
  ('qet:manual-valve', 'qet', 'Manual valve', 'general', 910),
  ('qet:three-way-valve', 'qet', 'Three way valve', 'general', 920),
  ('qet:motorised-valve', 'qet', 'Motorised valve', 'general', 930),
  ('qet:motorised-three-way-valve', 'qet', 'Motorised three way valve', 'general', 940),
  ('qet:solenoid-valve', 'qet', 'Solenoid valve', 'general', 950),
  ('qet:pressure-independent-control-valve', 'qet', 'Pressure independent control valve', 'general', 960),
  ('qet:directional-valve-two-two', 'qet', 'Directional valve two two', 'general', 970),
  ('qet:directional-valve-four-two', 'qet', 'Directional valve four two', 'general', 980),
  ('qet:butterfly-valve', 'qet', 'Butterfly valve', 'general', 990),
  ('qet:balancing-valve', 'qet', 'Balancing valve', 'general', 1000),
  ('qet:differential-pressure-valve', 'qet', 'Differential pressure valve', 'general', 1010),
  ('qet:safety-valve', 'qet', 'Safety valve', 'general', 1020),
  ('qet:globe-valve', 'qet', 'Globe valve', 'general', 1030),
  ('qet:gate-valve', 'qet', 'Gate valve', 'general', 1040),
  ('qet:ball-valve', 'qet', 'Ball valve', 'general', 1050),
  ('qet:diaphragm-valve', 'qet', 'Diaphragm valve', 'general', 1060),
  ('qet:bursting-disc', 'qet', 'Bursting disc', 'general', 1070),
  ('qet:spring-check-valve', 'qet', 'Spring check valve', 'general', 1080),
  ('qet:stop-valve', 'qet', 'Stop valve', 'general', 1090),
  ('qet:air-vent', 'qet', 'Air vent', 'general', 1100),
  ('qet:y-strainer', 'qet', 'Y strainer', 'general', 1110),
  ('qet:pressure-gauge', 'qet', 'Pressure gauge', 'environment', 1120),
  ('qet:differential-pressure-gauge', 'qet', 'Differential pressure gauge', 'environment', 1130),
  ('qet:thermometer', 'qet', 'Thermometer', 'environment', 1140),
  ('qet:flow-indicator', 'qet', 'Flow indicator', 'environment', 1150),
  ('qet:totalising-flowmeter', 'qet', 'Totalising flowmeter', 'environment', 1160),
  ('qet:level-indicator', 'qet', 'Level indicator', 'environment', 1170),
  ('qet:pressure-switch', 'qet', 'Pressure switch', 'environment', 1180),
  ('qet:pressure-sensor', 'qet', 'Pressure sensor', 'environment', 1190),
  ('qet:propeller-flowmeter', 'qet', 'Propeller flowmeter', 'environment', 1200),
  ('qet:dial-thermometer', 'qet', 'Dial thermometer', 'environment', 1210),
  ('qet:temperature-sensor', 'qet', 'Temperature sensor', 'environment', 1220),
  ('qet:flow-switch', 'qet', 'Flow switch', 'environment', 1230),
  ('qet:humidistat', 'qet', 'Humidistat', 'environment', 1240),
  ('qet:heat-meter', 'qet', 'Heat meter', 'environment', 1250),
  ('qet:outdoor-temperature-probe', 'qet', 'Outdoor temperature probe', 'environment', 1260),
  ('qet:air-quality-sensor', 'qet', 'Air quality sensor', 'environment', 1270),
  ('qet:co2-controller', 'qet', 'CO2 controller', 'environment', 1280),
  ('qet:flat-plate-solar-collector', 'qet', 'Flat plate solar collector', 'environment', 1290),
  ('qet:electric-water-heater', 'qet', 'Electric water heater', 'facility', 1300),
  ('qet:instantaneous-water-heater', 'qet', 'Instantaneous water heater', 'facility', 1310),
  ('qet:time-switch', 'qet', 'Time switch', 'facility', 1320),
  ('qet:wall-controller', 'qet', 'Wall controller', 'facility', 1330),
  ('qet:emergency-light', 'qet', 'Emergency light', 'facility', 1340),
  ('qet:electrical-panel', 'qet', 'Electrical panel', 'electrical', 1350),
  ('qet:light-switch', 'qet', 'Light switch', 'electrical', 1360),
  ('qet:immersion-heater', 'qet', 'Immersion heater', 'electrical', 1370),
  ('wmpid:container-tank-cistern', 'wmpid', 'Container tank cistern', 'water', 10),
  ('wmpid:closed-tank-with-conical-bottom', 'wmpid', 'Closed tank with conical bottom', 'water', 20),
  ('wmpid:tank-vessel', 'wmpid', 'Tank vessel', 'water', 30),
  ('wmpid:tank-with-conical-roof-and-flat-bottom', 'wmpid', 'Tank with conical roof and flat bottom', 'water', 40),
  ('wmpid:tank-vessel-with-dished-ends', 'wmpid', 'Tank vessel with dished ends', 'water', 50),
  ('wmpid:vessel-with-dished-roof-and-conical-bottom', 'wmpid', 'Vessel with dished roof and conical bottom', 'water', 60),
  ('wmpid:vessel-with-conical-roof-and-bottom', 'wmpid', 'Vessel with conical roof and bottom', 'water', 70),
  ('wmpid:vessel-with-dished-ends-and-support-legs', 'wmpid', 'Vessel with dished ends and support legs', 'water', 80),
  ('wmpid:vessel-with-dished-ends-and-heating-or-cooling', 'wmpid', 'Vessel with dished ends and heating or cooling', 'water', 90),
  ('wmpid:vessel-with-dished-ends-and-electrical-heating', 'wmpid', 'Vessel with dished ends and electrical heating', 'water', 100),
  ('wmpid:vessel-with-dished-bottom-and-surface-indication', 'wmpid', 'Vessel with dished bottom and surface indication', 'water', 110),
  ('wmpid:vessel-with-full-tube-heating-or-cooling-coil', 'wmpid', 'Vessel with full tube heating or cooling coil', 'water', 120),
  ('wmpid:jacketed-vessel-with-agitator', 'wmpid', 'Jacketed vessel with agitator', 'water', 130),
  ('wmpid:spherical-vessel', 'wmpid', 'Spherical vessel', 'water', 140),
  ('wmpid:pressurized-vessel-horizontal', 'wmpid', 'Pressurized vessel horizontal', 'water', 150),
  ('wmpid:knock-out-drum', 'wmpid', 'Knock out drum', 'water', 160),
  ('wmpid:barrel-drum', 'wmpid', 'Barrel drum', 'water', 170),
  ('wmpid:liquid-filter-general', 'wmpid', 'Liquid filter general', 'water', 180),
  ('wmpid:liquid-filter-cartridge-type', 'wmpid', 'Liquid filter cartridge type', 'water', 190),
  ('wmpid:rotary-drum-filter', 'wmpid', 'Rotary drum filter', 'water', 200),
  ('wmpid:belt-filter', 'wmpid', 'Belt filter', 'water', 210),
  ('wmpid:fixed-bed-filter', 'wmpid', 'Fixed bed filter', 'water', 220),
  ('wmpid:filter', 'wmpid', 'Filter', 'water', 230),
  ('wmpid:suction-filter', 'wmpid', 'Suction filter', 'water', 240),
  ('wmpid:strainer', 'wmpid', 'Strainer', 'water', 250),
  ('wmpid:screen-general', 'wmpid', 'Screen general', 'water', 260),
  ('wmpid:screen-coarse-rake', 'wmpid', 'Screen coarse rake', 'water', 270),
  ('wmpid:settling-chamber', 'wmpid', 'Settling chamber', 'water', 280),
  ('wmpid:waste-water-solidifier-open', 'wmpid', 'Waste water solidifier open', 'water', 290),
  ('wmpid:in-line-static-mixer', 'wmpid', 'In line static mixer', 'water', 300),
  ('wmpid:in-line-rotary-mixer', 'wmpid', 'In line rotary mixer', 'water', 310),
  ('wmpid:agitator-general', 'wmpid', 'Agitator general', 'water', 320),
  ('wmpid:agitator-turbine-type', 'wmpid', 'Agitator turbine type', 'water', 330),
  ('wmpid:agitator-propeller-type', 'wmpid', 'Agitator propeller type', 'water', 340),
  ('wmpid:agitator-paddle-type', 'wmpid', 'Agitator paddle type', 'water', 350),
  ('wmpid:spray-nozzle', 'wmpid', 'Spray nozzle', 'water', 360),
  ('wmpid:breaker', 'wmpid', 'Breaker', 'electrical', 370),
  ('wmpid:diode', 'wmpid', 'Diode', 'electrical', 380),
  ('wmpid:electric-motor', 'wmpid', 'Electric motor', 'electrical', 390),
  ('wmpid:electric-motor-ac', 'wmpid', 'Electric motor AC', 'electrical', 400),
  ('wmpid:electric-motor-dc', 'wmpid', 'Electric motor DC', 'electrical', 410),
  ('wmpid:generator', 'wmpid', 'Generator', 'electrical', 420),
  ('wmpid:generator-ac', 'wmpid', 'Generator AC', 'electrical', 430),
  ('wmpid:generator-dc', 'wmpid', 'Generator DC', 'electrical', 440),
  ('wmpid:heat-exchanger-no-cross', 'wmpid', 'Heat exchanger no cross', 'hvac', 450),
  ('wmpid:plate-heat-exchanger', 'wmpid', 'Plate heat exchanger', 'hvac', 460),
  ('wmpid:double-pipe-heat-exchanger', 'wmpid', 'Double pipe heat exchanger', 'hvac', 470),
  ('wmpid:u-shaped-tubes-heat-exchanger', 'wmpid', 'U shaped tubes heat exchanger', 'hvac', 480),
  ('wmpid:spiral-heat-exchanger', 'wmpid', 'Spiral heat exchanger', 'hvac', 490),
  ('wmpid:condenser', 'wmpid', 'Condenser', 'hvac', 500),
  ('wmpid:finned-tube-heat-exchanger', 'wmpid', 'Finned tube heat exchanger', 'hvac', 510),
  ('wmpid:finned-tube-heat-exchanger-with-fan', 'wmpid', 'Finned tube heat exchanger with fan', 'hvac', 520),
  ('wmpid:floating-head-heat-exchanger', 'wmpid', 'Floating head heat exchanger', 'hvac', 530),
  ('wmpid:tube-bundle-heat-exchanger', 'wmpid', 'Tube bundle heat exchanger', 'hvac', 540),
  ('wmpid:air-cooler', 'wmpid', 'Air cooler', 'hvac', 550),
  ('wmpid:cooler', 'wmpid', 'Cooler', 'hvac', 560),
  ('wmpid:heater', 'wmpid', 'Heater', 'hvac', 570),
  ('wmpid:electric-heater', 'wmpid', 'Electric heater', 'hvac', 580),
  ('wmpid:cooling-tower', 'wmpid', 'Cooling tower', 'hvac', 590),
  ('wmpid:wet-cooling-tower', 'wmpid', 'Wet cooling tower', 'hvac', 600),
  ('wmpid:cooling-tower-general', 'wmpid', 'Cooling tower general', 'hvac', 610),
  ('wmpid:dry-cooling-tower-forced-draught', 'wmpid', 'Dry cooling tower forced draught', 'hvac', 620),
  ('wmpid:wet-cooling-tower-forced-draught', 'wmpid', 'Wet cooling tower forced draught', 'hvac', 630),
  ('wmpid:axial-fan', 'wmpid', 'Axial fan', 'hvac', 640),
  ('wmpid:radial-fan', 'wmpid', 'Radial fan', 'hvac', 650),
  ('wmpid:fan', 'wmpid', 'Fan', 'hvac', 660),
  ('wmpid:back-draft-damper', 'wmpid', 'Back draft damper', 'hvac', 670),
  ('wmpid:fire-damper', 'wmpid', 'Fire damper', 'hvac', 680),
  ('wmpid:smoke-damper', 'wmpid', 'Smoke damper', 'hvac', 690),
  ('wmpid:louvre-damper', 'wmpid', 'Louvre damper', 'hvac', 700),
  ('wmpid:throttle-damper', 'wmpid', 'Throttle damper', 'hvac', 710),
  ('wmpid:air-filter', 'wmpid', 'Air filter', 'hvac', 720),
  ('wmpid:air-humidifier', 'wmpid', 'Air humidifier', 'hvac', 730),
  ('wmpid:air-heater', 'wmpid', 'Air heater', 'hvac', 740),
  ('wmpid:air-cooling-coil', 'wmpid', 'Air cooling coil', 'hvac', 750),
  ('wmpid:air-mixing-chamber', 'wmpid', 'Air mixing chamber', 'hvac', 760),
  ('wmpid:supply-air-outlet', 'wmpid', 'Supply air outlet', 'hvac', 770),
  ('wmpid:constant-air-volume-controller', 'wmpid', 'Constant air volume controller', 'hvac', 780),
  ('wmpid:variable-air-volume-controller', 'wmpid', 'Variable air volume controller', 'hvac', 790),
  ('wmpid:rigid-air-duct', 'wmpid', 'Rigid air duct', 'hvac', 800),
  ('wmpid:compressor', 'wmpid', 'Compressor', 'mechanical', 810),
  ('wmpid:vacuum-pump-or-compressor', 'wmpid', 'Vacuum pump or compressor', 'mechanical', 820),
  ('wmpid:turbo-compressor', 'wmpid', 'Turbo compressor', 'mechanical', 830),
  ('wmpid:piston-compressor', 'wmpid', 'Piston compressor', 'mechanical', 840),
  ('wmpid:compressor-general', 'wmpid', 'Compressor general', 'mechanical', 850),
  ('wmpid:compressor-centrifugal', 'wmpid', 'Compressor centrifugal', 'mechanical', 860),
  ('wmpid:compressor-screw', 'wmpid', 'Compressor screw', 'mechanical', 870),
  ('wmpid:compressor-turbo', 'wmpid', 'Compressor turbo', 'mechanical', 880),
  ('wmpid:compressor-reciprocating-piston', 'wmpid', 'Compressor reciprocating piston', 'mechanical', 890),
  ('wmpid:dryer', 'wmpid', 'Dryer', 'mechanical', 900),
  ('wmpid:drier-general', 'wmpid', 'Drier general', 'mechanical', 910),
  ('wmpid:turbine', 'wmpid', 'Turbine', 'mechanical', 920),
  ('wmpid:boiler-with-dome', 'wmpid', 'Boiler with dome', 'mechanical', 930),
  ('wmpid:steam-generator', 'wmpid', 'Steam generator', 'mechanical', 940),
  ('wmpid:furnace', 'wmpid', 'Furnace', 'mechanical', 950),
  ('wmpid:gearbox', 'wmpid', 'Gearbox', 'mechanical', 960),
  ('wmpid:centrifuge', 'wmpid', 'Centrifuge', 'mechanical', 970),
  ('wmpid:cyclone-separator', 'wmpid', 'Cyclone separator', 'mechanical', 980),
  ('wmpid:sensor-probe', 'wmpid', 'Sensor probe', 'environment', 990),
  ('wmpid:controller', 'wmpid', 'Controller', 'environment', 1000),
  ('wmpid:orifice-plate', 'wmpid', 'Orifice plate', 'environment', 1010),
  ('wmpid:gas-filter', 'wmpid', 'Gas filter', 'environment', 1020),
  ('wmpid:bag-filter', 'wmpid', 'Bag filter', 'environment', 1030),
  ('wmpid:wet-scrubber', 'wmpid', 'Wet scrubber', 'environment', 1040),
  ('wmpid:electrostatic-precipitator', 'wmpid', 'Electrostatic precipitator', 'environment', 1050),
  ('wmpid:stack', 'wmpid', 'Stack', 'environment', 1060),
  ('wmpid:gas-flare', 'wmpid', 'Gas flare', 'environment', 1070),
  ('wmpid:vent-to-atmosphere', 'wmpid', 'Vent to atmosphere', 'environment', 1080),
  ('wmpid:dust-trap', 'wmpid', 'Dust trap', 'environment', 1090),
  ('wmpid:silencer', 'wmpid', 'Silencer', 'environment', 1100),
  ('wmpid:lift', 'wmpid', 'Lift', 'facility', 1110),
  ('wmpid:crane', 'wmpid', 'Crane', 'facility', 1120),
  ('wmpid:pump', 'wmpid', 'Pump', 'general', 1130),
  ('wmpid:pump-centrifugal', 'wmpid', 'Pump centrifugal', 'general', 1140),
  ('wmpid:pump-diaphragm', 'wmpid', 'Pump diaphragm', 'general', 1150),
  ('wmpid:pump-reciprocating-piston', 'wmpid', 'Pump reciprocating piston', 'general', 1160),
  ('wmpid:pump-progressive-cavity', 'wmpid', 'Pump progressive cavity', 'general', 1170),
  ('wmpid:pump-screw', 'wmpid', 'Pump screw', 'general', 1180),
  ('wmpid:pump-gear', 'wmpid', 'Pump gear', 'general', 1190),
  ('wmpid:pump-liquid-general', 'wmpid', 'Pump liquid general', 'general', 1200),
  ('wmpid:ejector-pump', 'wmpid', 'Ejector pump', 'general', 1210),
  ('wmpid:ball-valve', 'wmpid', 'Ball valve', 'general', 1220),
  ('wmpid:butterfly-valve', 'wmpid', 'Butterfly valve', 'general', 1230),
  ('wmpid:check-valve', 'wmpid', 'Check valve', 'general', 1240),
  ('wmpid:control-valve', 'wmpid', 'Control valve', 'general', 1250),
  ('wmpid:diaphragm-valve', 'wmpid', 'Diaphragm valve', 'general', 1260),
  ('wmpid:globe-valve', 'wmpid', 'Globe valve', 'general', 1270),
  ('wmpid:gate-valve', 'wmpid', 'Gate valve', 'general', 1280),
  ('wmpid:needle-valve', 'wmpid', 'Needle valve', 'general', 1290),
  ('wmpid:motor-operated-valve', 'wmpid', 'Motor operated valve', 'general', 1300),
  ('wmpid:pressure-reducing-valve', 'wmpid', 'Pressure reducing valve', 'general', 1310),
  ('wmpid:steam-trap', 'wmpid', 'Steam trap', 'general', 1320),
  ('wmpid:three-way-valve', 'wmpid', 'Three way valve', 'general', 1330),
  ('wmpid:valve-general', 'wmpid', 'Valve general', 'general', 1340),
  ('wmpid:valve-angle', 'wmpid', 'Valve angle', 'general', 1350),
  ('wmpid:valve-globe-type', 'wmpid', 'Valve globe type', 'general', 1360),
  ('wmpid:valve-ball-type', 'wmpid', 'Valve ball type', 'general', 1370),
  ('wmpid:valve-gate-type', 'wmpid', 'Valve gate type', 'general', 1380),
  ('wmpid:valve-butterfly-form-1', 'wmpid', 'Valve butterfly form 1', 'general', 1390),
  ('wmpid:valve-control-continuous', 'wmpid', 'Valve control continuous', 'general', 1400),
  ('wmpid:valve-three-way-general', 'wmpid', 'Valve three way general', 'general', 1410),
  ('wmpid:check-valve-general', 'wmpid', 'Check valve general', 'general', 1420),
  ('wmpid:swing-check-valve-form-1', 'wmpid', 'Swing check valve form 1', 'general', 1430),
  ('wmpid:safety-valve-globe', 'wmpid', 'Safety valve globe', 'general', 1440),
  ('wmpid:breather-valve', 'wmpid', 'Breather valve', 'general', 1450),
  ('wmpid:actuator-manual', 'wmpid', 'Actuator manual', 'general', 1460),
  ('wmpid:actuator-diaphragm', 'wmpid', 'Actuator diaphragm', 'general', 1470),
  ('wmpid:actuator-motor', 'wmpid', 'Actuator motor', 'general', 1480),
  ('wmpid:actuator-general', 'wmpid', 'Actuator general', 'general', 1490),
  ('wmpid:pipe', 'wmpid', 'Pipe', 'general', 1500),
  ('wmpid:pipeline', 'wmpid', 'Pipeline', 'general', 1510),
  ('wmpid:insulated-pipe', 'wmpid', 'Insulated pipe', 'general', 1520),
  ('wmpid:reducer', 'wmpid', 'Reducer', 'general', 1530),
  ('wmpid:flanged-connection', 'wmpid', 'Flanged connection', 'general', 1540),
  ('wmpid:rupture-disc', 'wmpid', 'Rupture disc', 'general', 1550),
  ('wmpid:viewing-glass', 'wmpid', 'Viewing glass', 'general', 1560),
  ('wmpid:gas-bottle', 'wmpid', 'Gas bottle', 'general', 1570),
  ('drawio:tank', 'drawio', 'Tank', 'water', 10),
  ('drawio:tank-conical-bottom', 'drawio', 'Tank conical bottom', 'water', 20),
  ('drawio:tank-conical-roof', 'drawio', 'Tank conical roof', 'water', 30),
  ('drawio:tank-dished-roof', 'drawio', 'Tank dished roof', 'water', 40),
  ('drawio:tank-floating-roof', 'drawio', 'Tank floating roof', 'water', 50),
  ('drawio:concrete-tank', 'drawio', 'Concrete tank', 'water', 60),
  ('drawio:double-concrete-tank', 'drawio', 'Double concrete tank', 'water', 70),
  ('drawio:settling-tank', 'drawio', 'Settling tank', 'water', 80),
  ('drawio:container-tank-cistern', 'drawio', 'Container tank cistern', 'water', 90),
  ('drawio:pressurized-vessel', 'drawio', 'Pressurized vessel', 'water', 100),
  ('drawio:storage-sphere', 'drawio', 'Storage sphere', 'water', 110),
  ('drawio:vessel-dome', 'drawio', 'Vessel dome', 'water', 120),
  ('drawio:filter', 'drawio', 'Filter', 'water', 130),
  ('drawio:liquid-filter', 'drawio', 'Liquid filter', 'water', 140),
  ('drawio:liquid-filter-ion-exchanger', 'drawio', 'Liquid filter ion exchanger', 'water', 150),
  ('drawio:liquid-filter-bag-candle-cartridge', 'drawio', 'Liquid filter bag candle cartridge', 'water', 160),
  ('drawio:liquid-filter-fixed-bed', 'drawio', 'Liquid filter fixed bed', 'water', 170),
  ('drawio:press-filter', 'drawio', 'Press filter', 'water', 180),
  ('drawio:submersible-pump', 'drawio', 'Submersible pump', 'water', 190),
  ('drawio:sump-pump', 'drawio', 'Sump pump', 'water', 200),
  ('drawio:knife-valve', 'drawio', 'Knife valve', 'water', 210),
  ('drawio:pinch-valve', 'drawio', 'Pinch valve', 'water', 220),
  ('drawio:screening-device-sieve-strainer-coarse-rake', 'drawio', 'Screening device sieve strainer coarse rake', 'water', 230),
  ('drawio:centrifuge-decanter-screw-solid-shell', 'drawio', 'Centrifuge decanter screw solid shell', 'water', 240),
  ('drawio:centrifugal-pump-1', 'drawio', 'Centrifugal pump 1', 'general', 250),
  ('drawio:centrifugal-pump-2', 'drawio', 'Centrifugal pump 2', 'general', 260),
  ('drawio:feed-pump', 'drawio', 'Feed pump', 'general', 270),
  ('drawio:gear-pump', 'drawio', 'Gear pump', 'general', 280),
  ('drawio:peristaltic', 'drawio', 'Peristaltic', 'general', 290),
  ('drawio:screw-pump', 'drawio', 'Screw pump', 'general', 300),
  ('drawio:vacuum-pump', 'drawio', 'Vacuum pump', 'general', 310),
  ('drawio:vertical-pump', 'drawio', 'Vertical pump', 'general', 320),
  ('drawio:diaphragm', 'drawio', 'Diaphragm', 'general', 330),
  ('drawio:eccentric-worm', 'drawio', 'Eccentric worm', 'general', 340),
  ('drawio:reciprocating', 'drawio', 'Reciprocating', 'general', 350),
  ('drawio:pump-positive-displacement', 'drawio', 'Pump positive displacement', 'general', 360),
  ('drawio:pump-progressive-cavity', 'drawio', 'Pump progressive cavity', 'general', 370),
  ('drawio:ball-valve', 'drawio', 'Ball valve', 'general', 380),
  ('drawio:butterfly-valve-1', 'drawio', 'Butterfly valve 1', 'general', 390),
  ('drawio:check-valve-1', 'drawio', 'Check valve 1', 'general', 400),
  ('drawio:check-valve-2', 'drawio', 'Check valve 2', 'general', 410),
  ('drawio:gate-valve', 'drawio', 'Gate valve', 'general', 420),
  ('drawio:manual-operated-valve', 'drawio', 'Manual operated valve', 'general', 430),
  ('drawio:three-way-valve', 'drawio', 'Three way valve', 'general', 440),
  ('drawio:relief-prv', 'drawio', 'Relief prv', 'general', 450),
  ('drawio:safety-psv-1', 'drawio', 'Safety psv 1', 'general', 460),
  ('drawio:diverter-valve', 'drawio', 'Diverter valve', 'general', 470),
  ('drawio:rotary-valve', 'drawio', 'Rotary valve', 'general', 480),
  ('drawio:y-type-strainer', 'drawio', 'Y type strainer', 'general', 490),
  ('drawio:condenser', 'drawio', 'Condenser', 'hvac', 500),
  ('drawio:double-pipe-heat-exchanger', 'drawio', 'Double pipe heat exchanger', 'hvac', 510),
  ('drawio:electric-heater', 'drawio', 'Electric heater', 'hvac', 520),
  ('drawio:heater', 'drawio', 'Heater', 'hvac', 530),
  ('drawio:heat-exchanger-finned-tubes-fan', 'drawio', 'Heat exchanger finned tubes fan', 'hvac', 540),
  ('drawio:plate-and-frame-heat-exchanger', 'drawio', 'Plate and frame heat exchanger', 'hvac', 550),
  ('drawio:shell-and-tube-heat-exchanger-1', 'drawio', 'Shell and tube heat exchanger 1', 'hvac', 560),
  ('drawio:spiral-heat-exchanger', 'drawio', 'Spiral heat exchanger', 'hvac', 570),
  ('drawio:chiller', 'drawio', 'Chiller', 'hvac', 580),
  ('drawio:cooling-tower', 'drawio', 'Cooling tower', 'hvac', 590),
  ('drawio:cooling-tower-wet-induced-draught', 'drawio', 'Cooling tower wet induced draught', 'hvac', 600),
  ('drawio:cooler', 'drawio', 'Cooler', 'hvac', 610),
  ('drawio:fan', 'drawio', 'Fan', 'hvac', 620),
  ('drawio:forced-flow-air-cooler', 'drawio', 'Forced flow air cooler', 'hvac', 630),
  ('drawio:air-filter', 'drawio', 'Air filter', 'hvac', 640),
  ('drawio:ac-air-compressor', 'drawio', 'AC air compressor', 'mechanical', 650),
  ('drawio:centrifugal-compressor', 'drawio', 'Centrifugal compressor', 'mechanical', 660),
  ('drawio:compressor', 'drawio', 'Compressor', 'mechanical', 670),
  ('drawio:reciprocating-compressor', 'drawio', 'Reciprocating compressor', 'mechanical', 680),
  ('drawio:compressor-screw', 'drawio', 'Compressor screw', 'mechanical', 690),
  ('drawio:compressor-rotary', 'drawio', 'Compressor rotary', 'mechanical', 700),
  ('drawio:compressor-diaphragm', 'drawio', 'Compressor diaphragm', 'mechanical', 710),
  ('drawio:compressor-turbo', 'drawio', 'Compressor turbo', 'mechanical', 720),
  ('drawio:gas-blower', 'drawio', 'Gas blower', 'mechanical', 730),
  ('drawio:agitator-stirrer', 'drawio', 'Agitator stirrer', 'mechanical', 740),
  ('drawio:agitator-anchor', 'drawio', 'Agitator anchor', 'mechanical', 750),
  ('drawio:agitator-propeller', 'drawio', 'Agitator propeller', 'mechanical', 760),
  ('drawio:agitator-turbine', 'drawio', 'Agitator turbine', 'mechanical', 770),
  ('drawio:in-line-static-mixer', 'drawio', 'In line static mixer', 'mechanical', 780),
  ('drawio:in-line-rotary-mixer', 'drawio', 'In line rotary mixer', 'mechanical', 790),
  ('drawio:boiler-dome', 'drawio', 'Boiler dome', 'mechanical', 800),
  ('drawio:firing-system-burner', 'drawio', 'Firing system burner', 'mechanical', 810),
  ('drawio:turbine', 'drawio', 'Turbine', 'mechanical', 820),
  ('drawio:coriolis', 'drawio', 'Coriolis', 'environment', 830),
  ('drawio:magnetic', 'drawio', 'Magnetic', 'environment', 840),
  ('drawio:pitot-tube', 'drawio', 'Pitot tube', 'environment', 850),
  ('drawio:rotameter', 'drawio', 'Rotameter', 'environment', 860),
  ('drawio:ultrasonic', 'drawio', 'Ultrasonic', 'environment', 870),
  ('drawio:venturi', 'drawio', 'Venturi', 'environment', 880),
  ('drawio:vortex', 'drawio', 'Vortex', 'environment', 890),
  ('drawio:weir', 'drawio', 'Weir', 'environment', 900),
  ('drawio:stack-chimney', 'drawio', 'Stack chimney', 'environment', 910),
  ('drawio:gas-flare', 'drawio', 'Gas flare', 'environment', 920),
  ('drawio:cyclone', 'drawio', 'Cyclone', 'environment', 930),
  ('drawio:spray-scrubber', 'drawio', 'Spray scrubber', 'environment', 940),
  ('drawio:separator-electrostatic-precipitator', 'drawio', 'Separator electrostatic precipitator', 'environment', 950),
  ('drawio:thermocouple', 'drawio', 'Thermocouple', 'environment', 960),
  ('drawio:thermistor-1', 'drawio', 'Thermistor 1', 'environment', 970),
  ('drawio:electric-motor-ac', 'drawio', 'Electric motor AC', 'electrical', 980),
  ('drawio:electric-motor-dc', 'drawio', 'Electric motor DC', 'electrical', 990),
  ('drawio:transformer', 'drawio', 'Transformer', 'electrical', 1000),
  ('drawio:transformer-1', 'drawio', 'Transformer 1', 'electrical', 1010),
  ('drawio:current-transformer-2', 'drawio', 'Current transformer 2', 'electrical', 1020),
  ('drawio:potential-transformer', 'drawio', 'Potential transformer', 'electrical', 1030),
  ('drawio:adjustable-transformer', 'drawio', 'Adjustable transformer', 'electrical', 1040),
  ('drawio:circuit-breaker', 'drawio', 'Circuit breaker', 'electrical', 1050),
  ('drawio:isolator', 'drawio', 'Isolator', 'electrical', 1060),
  ('drawio:fuse', 'drawio', 'Fuse', 'electrical', 1070),
  ('drawio:switch-disconnector', 'drawio', 'Switch disconnector', 'electrical', 1080),
  ('drawio:dpdt', 'drawio', 'Dpdt', 'electrical', 1090),
  ('drawio:relay', 'drawio', 'Relay', 'electrical', 1100),
  ('drawio:relay-coil', 'drawio', 'Relay coil', 'electrical', 1110),
  ('drawio:pushbutton-make', 'drawio', 'Pushbutton make', 'electrical', 1120),
  ('drawio:pressure-actuated', 'drawio', 'Pressure actuated', 'electrical', 1130),
  ('drawio:temperature-actuated', 'drawio', 'Temperature actuated', 'electrical', 1140),
  ('drawio:flow-actuated', 'drawio', 'Flow actuated', 'electrical', 1150),
  ('drawio:proximity-limit-switch', 'drawio', 'Proximity limit switch', 'electrical', 1160),
  ('drawio:motor-2', 'drawio', 'Motor 2', 'electrical', 1170),
  ('drawio:line-cable', 'drawio', 'Line cable', 'electrical', 1180),
  ('drawio:cable-group', 'drawio', 'Cable group', 'electrical', 1190),
  ('drawio:ampermeter', 'drawio', 'Ampermeter', 'electrical', 1200),
  ('drawio:galvanometer', 'drawio', 'Galvanometer', 'electrical', 1210),
  ('drawio:oscilloscope', 'drawio', 'Oscilloscope', 'electrical', 1220),
  ('drawio:surge-protector-2', 'drawio', 'Surge protector 2', 'electrical', 1230),
  ('drawio:terminal-board', 'drawio', 'Terminal board', 'electrical', 1240),
  ('drawio:monocell-battery', 'drawio', 'Monocell battery', 'it_ups', 1250),
  ('drawio:multicell-battery', 'drawio', 'Multicell battery', 'it_ups', 1260),
  ('drawio:light-bulb', 'drawio', 'Light bulb', 'facility', 1270),
  ('drawio:lamp-1', 'drawio', 'Lamp 1', 'facility', 1280),
  ('drawio:bell', 'drawio', 'Bell', 'facility', 1290),
  ('drawio:buzzer', 'drawio', 'Buzzer', 'facility', 1300),
  ('drawio:lift', 'drawio', 'Lift', 'facility', 1310)
ON CONFLICT DO NOTHING;

RESET ROLE;

DO $$
BEGIN
  IF (SELECT count(*) FROM bms.mimic_symbol_libraries WHERE active) <> 7 THEN
    RAISE EXCEPTION 'migration 0092: expected 7 active symbol libraries';
  END IF;
  IF (SELECT count(*) FROM bms.mimic_symbols WHERE library_code = 'qet' AND active) <> 137 THEN
    RAISE EXCEPTION 'migration 0092: expected 137 active qet symbols';
  END IF;
  IF (SELECT count(*) FROM bms.mimic_symbols WHERE library_code = 'wmpid' AND active) <> 157 THEN
    RAISE EXCEPTION 'migration 0092: expected 157 active wmpid symbols';
  END IF;
  IF (SELECT count(*) FROM bms.mimic_symbols WHERE library_code = 'drawio' AND active) <> 131 THEN
    RAISE EXCEPTION 'migration 0092: expected 131 active drawio symbols';
  END IF;
  -- has_table_privilege follows role membership, so a write privilege bms_tenant inherits from
  -- another role is caught here (the 0085/0090 shape).
  IF has_table_privilege('bms_tenant', 'bms.mimic_symbols', 'INSERT') THEN
    RAISE EXCEPTION 'migration 0092: bms_tenant holds INSERT on bms.mimic_symbols';
  END IF;
  IF NOT has_table_privilege('bms_tenant', 'bms.mimic_symbols', 'SELECT') THEN
    RAISE EXCEPTION 'migration 0092: bms_tenant cannot read bms.mimic_symbols';
  END IF;
END $$;
