// GENERATED by scripts/mimic-symbols/generate.mjs from jgraph/drawio stencils (pid, electrical) 29.3.2 — do not edit by hand.
// draw.io — CC BY 4.0. The full licence notice is `DRAWIO_LICENCE_NOTICE` in
// apps/web/src/components/widgets/mimic-symbol-libraries/drawio.generated.ts (ADR 0084 decision 5).

import type { DrawioSymbolKey } from "@bms/shared";

import type { MimicShape } from "./shapes";

/** A line recording the conversion, then the draw.io licence verbatim from the release; the palette shows it. */
export const DRAWIO_LICENCE_NOTICE = `Converted by scripts/mimic-symbols/generate.mjs from the pid and electrical stencil sets of jgraph/drawio 29.3.2 into shape arrays of their geometry (text, colour and connection points dropped; each stencil fitted to a 24-unit box); the drawings are otherwise unchanged.

Pinned at jgraph/drawio@48b181339578e11da7052ebf5b1fba8499418b77 (v29.3.2, 2026-01-17).

The README at the pin, section "License":

The minified code authored by us in this repo is licensed under an Apache v2 license, but not all the sources to build those files are in this repo. This is not an open source project. We do not accept PRs.

The JGraph provided icons and diagram templates are licensed under the CC BY 4.0. Additional terms may also apply where the icons are originally defined by a third-party copyright holder. We have checked in all cases that the original license allows use in this project. Also see the terms for using the draw.io logo below.

Additional minified JavaScript files and Java libraries are used in this project. All of the licenses are deemed compatible with the Apache 2.0, nothing is GPL or AGPL, due diligence is performed on all third-party code.

We make no copyright claim on the content you create with this software, regardless of the copyright of individual icons used in such content.

src/main/webapp/stencils/LICENSE at the pin:

The icon sets and stencil libraries included in this software, and any derivatives thereof 
(including conversions to other formats, traced reproductions, or substantially similar visual 
representations), may not be displayed within, distributed for use with, or incorporated into 
products distributed through the Atlassian marketplace or plugin ecosystem, without explicit 
written permission.

Licence URI: https://creativecommons.org/licenses/by/4.0/

Attribution: JGraph Ltd, draw.io`;

/** Each draw.io key's shape elements, geometry attributes only (ADR 0084 decision 5). */
export const DRAWIO_SHAPES: Readonly<Record<DrawioSymbolKey, readonly MimicShape[]>> = {
  "drawio:tank": [["path", { d: "M17.03 1.93 L17.03 22.07 A3.27 1.26 0 0 1 6.97 22.07 L6.97 1.93 A3.27 1.26 0 0 1 17.03 1.93 Z M6.97 1.93 L17.03 1.93 M6.97 22.07 L17.03 22.07" }]],
  "drawio:tank-conical-bottom": [["path", { d: "M0 16.8 L0 0 L24 0 L24 16.8 L12 24 Z M0 16.8 L24 16.8" }]],
  "drawio:tank-conical-roof": [["path", { d: "M0 6 L0 22.8 L24 22.8 L24 6 L12 1.2 Z M0 6 L24 6" }]],
  "drawio:tank-dished-roof": [["rect", { x: "0", y: "6.66", width: "24", height: "16.8" }], ["path", { d: "M0 6.66 A18 18 0 0 1 24 6.66 Z" }]],
  "drawio:tank-floating-roof": [["path", { d: "M0 3.6 L0 20.4 L24 20.4 L24 3.6 L22.8 3.6 L22.8 4.8 L1.2 4.8 L1.2 3.6 Z" }], ["path", { d: "M0 3.6 L0 20.4 L24 20.4 L24 3.6 M1.2 3.6 L1.2 4.8 L22.8 4.8 L22.8 3.6" }]],
  "drawio:concrete-tank": [["path", { d: "M0 6.38 L1.5 6.38 L1.5 16.13 L22.5 16.13 L22.5 6.38 L24 6.38 L24 17.63 L0 17.63 Z M0 7.13 L0.75 6.38 M0 8.63 L1.5 7.13 M0 10.13 L1.5 8.63 M0 11.63 L1.5 10.13 M0 13.13 L1.5 11.63 M0 14.63 L1.5 13.13 M6 17.63 L7.5 16.13 M0 16.13 L1.5 14.63 M0 17.63 L1.5 16.13 M1.5 17.63 L3 16.13 M3 17.63 L4.5 16.13 M4.5 17.63 L6 16.13 M7.5 17.63 L9 16.13 M9 17.63 L10.5 16.13 M10.5 17.63 L12 16.13 M12 17.63 L13.5 16.13 M13.5 17.63 L15 16.13 M16.5 17.63 L18 16.13 M18 17.63 L19.5 16.13 M19.5 17.63 L21 16.13 M21 17.63 L24 14.63 M22.5 17.63 L24 16.13 M22.5 14.63 L24 13.13 M22.5 13.13 L24 11.63 M22.5 11.63 L24 10.13 M22.5 10.13 L24 8.63 M22.5 8.63 L24 7.13 M22.5 7.13 L23.25 6.38 M15 17.63 L16.5 16.13" }]],
  "drawio:double-concrete-tank": [["path", { d: "M0 17.63 L0 6.38 L1.5 6.38 L1.5 16.13 L11.25 16.13 L11.25 6.38 L12.75 6.38 L12.75 16.13 L22.5 16.13 L22.5 6.38 L24 6.38 L24 17.63 Z M0 7.13 L0.75 6.38 M0 8.63 L1.5 7.13 M0 10.13 L1.5 8.63 M0 11.63 L1.5 10.13 M0 13.13 L1.5 11.63 M0 14.63 L1.5 13.13 M6 17.63 L7.5 16.13 M0 16.13 L1.5 14.63 M0 17.63 L1.5 16.13 M1.5 17.63 L3 16.13 M3 17.63 L4.5 16.13 M4.5 17.63 L6 16.13 M7.5 17.63 L9 16.13 M9 17.63 L10.5 16.13 M10.5 17.63 L12.75 15.38 M12 17.63 L13.5 16.13 M13.5 17.63 L15 16.13 M16.5 17.63 L18 16.13 M18 17.63 L19.5 16.13 M19.5 17.63 L21 16.13 M21 17.63 L24 14.63 M22.5 17.63 L24 16.13 M22.5 14.63 L24 13.13 M22.5 13.13 L24 11.63 M22.5 11.63 L24 10.13 M22.5 10.13 L24 8.63 M22.5 8.63 L24 7.13 M22.5 7.13 L23.25 6.38 M15 17.63 L16.5 16.13 M11.25 15.38 L12.75 13.88 M11.25 13.88 L12.75 12.38 M11.25 12.38 L12.75 10.88 M11.25 10.88 L12.75 9.38 M11.25 9.38 L12.75 7.88 M11.25 7.88 L12.75 6.38" }]],
  "drawio:settling-tank": [["path", { d: "M0 2.4 L0 15.6 L12 21.6 L24 15.6 L24 2.4" }]],
  "drawio:container-tank-cistern": [["path", { d: "M0 3.6 L0 20.4 L24 20.4 L24 3.6" }]],
  "drawio:pressurized-vessel": [["path", { d: "M6 1.8 A6 1.8 0 1 1 18 1.8 L18 22.2 A6 1.8 0 1 1 6 22.2 Z" }]],
  "drawio:storage-sphere": [["rect", { x: "10.56", y: "18.72", width: "2.88", height: "2.88" }], ["rect", { x: "6.72", y: "0", width: "2.88", height: "2.88" }], ["rect", { x: "14.4", y: "0", width: "2.88", height: "2.88" }], ["path", { d: "M2.4 10.8 L2.4 24 L21.6 24 L21.6 10.8 M6 0 L10.32 0 M13.68 0 L18 0 M9.84 21.6 L14.16 21.6" }], ["ellipse", { cx: "12", cy: "10.8", rx: "9.6", ry: "9.6" }]],
  "drawio:vessel-dome": [["path", { d: "M22.07 8.84 A1.26 3.27 179.97 1 1 22.07 18.9 L1.94 18.91 A1.26 3.27 179.97 1 1 1.93 8.85 L13.26 8.84 L13.26 6.32 A2.52 1.26 179.97 0 1 18.29 6.32 L18.29 8.84 Z" }]],
  "drawio:filter": [["rect", { x: "0", y: "0", width: "24", height: "24" }], ["path", { d: "M24 0 L0 24" }]],
  "drawio:liquid-filter": [["rect", { x: "6", y: "0", width: "12", height: "24" }], ["path", { d: "M6 12 L18 12" }]],
  "drawio:liquid-filter-ion-exchanger": [["rect", { x: "6", y: "0", width: "12", height: "24" }], ["path", { d: "M6 4.8 L18 4.8 M6 19.2 L18 19.2" }]],
  "drawio:liquid-filter-bag-candle-cartridge": [["rect", { x: "6", y: "0", width: "12", height: "24" }], ["path", { d: "M6 4.8 L18 4.8 M6 19.2 L18 19.2 M6 9.6 L9.6 9.6 L9.6 14.4 L14.4 14.4 L14.4 9.6 L18 9.6" }]],
  "drawio:liquid-filter-fixed-bed": [["rect", { x: "6", y: "0", width: "12", height: "24" }], ["path", { d: "M6 4.8 L18 19.2 M18 4.8 L6 19.2" }], ["path", { d: "M6 4.8 L18 4.8 M6 19.2 L18 19.2" }]],
  "drawio:press-filter": [["rect", { x: "0", y: "6", width: "24", height: "12" }], ["path", { d: "M2.4 8.4 L2.4 15.6 M7.2 8.4 L7.2 15.6 M12 8.4 L12 15.6 M16.8 8.4 L16.8 15.6 M21.6 8.4 L21.6 15.6" }], ["path", { d: "M4.8 6 L4.8 18 M9.6 6 L9.6 18 M14.4 6 L14.4 18 M19.2 6 L19.2 18" }]],
  "drawio:submersible-pump": [["path", { d: "M22.43 12.7 A4.64 4.64 0 0 1 22.43 19.65 L1.57 19.65 A4.64 4.64 0 0 1 1.57 12.7 Z M17.79 10.73 L22.43 10.73 M20.11 10.73 L20.11 12.7" }], ["rect", { x: "3.89", y: "19.65", width: "16.23", height: "0.93" }], ["rect", { x: "7.36", y: "4.58", width: "9.27", height: "8.11" }], ["rect", { x: "10.38", y: "3.42", width: "3.25", height: "1.16" }]],
  "drawio:sump-pump": [["path", { d: "M17.78 20.14 A2.57 2.57 0 0 1 17.78 24 L6.22 24 A2.57 2.57 0 0 1 6.22 20.14 Z M10.07 0.87 A2.57 2.57 0 0 1 13.93 0.87 L13.93 4.72 A2.57 2.57 0 0 1 10.07 4.72 Z M15.21 19.05 L17.78 19.05 M16.5 19.05 L16.5 20.14 M10.07 4.72 L13.93 4.72 M10.07 0.87 L13.93 0.87" }], ["rect", { x: "11.74", y: "5.56", width: "0.51", height: "14.58" }], ["rect", { x: "7.5", y: "9.74", width: "9", height: "1.8" }], ["path", { d: "M7.5 10.64 L16.5 10.64" }]],
  "drawio:knife-valve": [["rect", { x: "8.4", y: "5.4", width: "7.2", height: "16.8" }], ["path", { d: "M0 12.6 L8.4 12.6 M15.6 12.6 L24 12.6 M7.2 1.8 L16.8 1.8 M12 1.8 L12 16.2 M14.4 13.8 L12 21 L9.6 13.8 L12 16.2 Z" }]],
  "drawio:pinch-valve": [["path", { d: "M0 19.35 L0 4.65 L24 19.35 L24 4.65 Z" }], ["path", { d: "M7.71 7.1 L12 9.72 L16.29 7.1 M7.71 16.9 L12 14.28 L16.29 16.9" }]],
  "drawio:screening-device-sieve-strainer-coarse-rake": [["path", { d: "M4 0 L20 0 L20 16 L12 24 L4 16 Z" }], ["path", { d: "M10.29 4.69 L11.7 3.28 L16.78 8.38 L15.36 9.79 M13.4 4.98 L11.98 6.39 M15.09 6.68 L13.67 8.09" }], ["path", { d: "M4.1 0.15 L20 15.9" }]],
  "drawio:centrifuge-decanter-screw-solid-shell": [["rect", { x: "2.18", y: "1.09", width: "21.82", height: "21.82" }], ["path", { d: "M21.82 3.27 L4.36 3.27 L4.36 20.73 L21.82 20.73 M0 12 L21.82 12 M6.55 12 L9.82 6.55 L16.36 17.45 L19.64 12" }]],
  "drawio:centrifugal-pump-1": [["path", { d: "M4.11 19.03 L0 23.49 L20.57 23.49 L16.46 19.03" }], ["path", { d: "M0.21 9.09 A10.29 10.29 0 0 1 10.29 0.51 L24 0.51 L24 7.37 L20.04 7.37 A10.29 10.29 0 1 1 0.21 12.51" }], ["path", { d: "M7.34 9.09 A3.43 3.43 0 1 1 7.34 12.51" }]],
  "drawio:centrifugal-pump-2": [["path", { d: "M6.06 19.95 L2.32 24 L21.02 24 L17.28 19.95" }], ["path", { d: "M10.12 21.63 A9.35 9.35 0 0 1 2.32 12.47 L2.32 0 L8.56 0 L8.56 3.6 A9.35 9.35 0 1 1 13.23 21.63" }], ["path", { d: "M10.12 15.15 A3.12 3.12 0 1 1 13.23 15.15" }]],
  "drawio:feed-pump": [["path", { d: "M0 7.2 L15.6 7.2 L15.6 9.6 L24 9.6 L24 14.4 L15.6 14.4 L15.6 16.8 L0 16.8 Z" }]],
  "drawio:gear-pump": [["path", { d: "M8.44 21.63 L6.46 24 L17.54 24 L15.53 21.63" }], ["path", { d: "M17.27 2.64 L17.27 19.78 A5.27 2.64 0 0 1 6.73 19.78 L6.73 2.64 A5.27 2.64 0 0 1 17.27 2.64 Z" }], ["ellipse", { cx: "12", cy: "6.07", rx: "4.22", ry: "4.22" }], ["ellipse", { cx: "12", cy: "15.82", rx: "4.22", ry: "4.22" }], ["path", { d: "M19.52 8.31 L19.52 13.58 M17.27 10.95 L19.52 10.95 M4.48 8.44 L4.48 13.71 M4.48 10.95 L6.73 10.95" }]],
  "drawio:peristaltic": [["path", { d: "M5.74 19.48 L1.57 24 L22.43 24 L18.26 19.48" }], ["ellipse", { cx: "12", cy: "11.13", rx: "10.43", ry: "10.43" }], ["ellipse", { cx: "12", cy: "4.17", rx: "3.48", ry: "3.48" }], ["ellipse", { cx: "6.3", cy: "15.13", rx: "3.48", ry: "3.48" }], ["ellipse", { cx: "17.7", cy: "15.13", rx: "3.48", ry: "3.48" }], ["path", { d: "M8.97 2.5 L3.17 13.57 M15.03 2.5 L20.83 13.57 M6.3 18.61 L17.7 18.61 M8.52 0 L8.52 4.17 M15.48 0 L15.48 4.17" }]],
  "drawio:screw-pump": [["path", { d: "M4.11 19.02 L0 23.48 L20.57 23.48 L16.46 19.02" }], ["path", { d: "M0.21 9.08 A10.29 10.29 0 0 1 20.49 9.08 L24 9.08 L24 12.51 L20.49 12.51 A10.29 10.29 0 0 1 0.21 12.51" }], ["path", { d: "M2.64 14.5 A4.46 4.46 0 0 0 10.29 10.79 A4.46 4.46 0 0 1 17.97 7.02" }]],
  "drawio:vacuum-pump": [["path", { d: "M0 11.52 L3.52 11.52 L3.52 9.58 L6.45 9.58 A6.06 6.06 0 0 1 17.55 9.58 L20.48 9.58 L20.48 11.52 L24 11.52 L24 12.48 L20.48 12.48 L20.48 14.42 L17.55 14.42 A6.06 6.06 0 0 1 6.45 14.42 L3.52 14.42 L3.52 12.48 L0 12.48 Z" }], ["path", { d: "M3.52 11.52 L3.52 12.48 M20.48 11.52 L20.48 12.48 M6.45 14.42 A6.06 6.06 0 0 1 6.45 9.58 M17.55 9.58 A6.06 6.06 0 0 1 17.55 14.42" }]],
  "drawio:vertical-pump": [["path", { d: "M9.55 1.11 A3.27 3.27 0 0 1 14.45 1.11 L14.45 15.82 A3.27 3.27 0 0 1 9.55 15.82 Z M19.36 19.09 A3.27 3.27 0 0 1 19.36 24 L4.64 24 A3.27 3.27 0 0 1 4.64 19.09 Z M20.42 21.55 L21.81 21.55 M21.81 19.91 L21.81 23.18 M2.19 21.55 L3.58 21.55 M2.19 19.91 L2.19 23.18 M9.55 15.82 L14.45 15.82 M9.55 1.11 L14.45 1.11" }], ["rect", { x: "11.67", y: "16.89", width: "0.65", height: "2.21" }]],
  "drawio:diaphragm": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M12 0 L24 12 A15.6 15.6 0 0 1 0 12 Z" }]],
  "drawio:eccentric-worm": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M0 12 L12 0 L24 12 M11.95 3.41 C11.95 3.41 10.42 4.18 11.9 6.05 C13.39 7.92 13.54 7.54 11.9 9.31 C10.27 11.09 9.5 11.38 11.95 13.78" }]],
  "drawio:reciprocating": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M0 12 L12 0 L24 12 M12 7.2 L12 12 M7.2 12 L16.8 12" }]],
  "drawio:pump-positive-displacement": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M12 0 L24 12 L12 24" }], ["rect", { x: "8.4", y: "8.4", width: "7.2", height: "7.2" }]],
  "drawio:pump-progressive-cavity": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M12 0 L24 12 L12 24 M6 12 A1.2 1.2 0 1 1 10.2 12 A1.2 1.2 0 1 0 13.8 12 A1.2 1.2 0 1 1 18 12" }]],
  "drawio:ball-valve": [["path", { d: "M0 4.65 L7.81 9.48 A4.9 4.9 0 0 1 16.21 9.48 L24 4.65 L24 19.35 L16.21 14.57 A4.9 4.9 0 0 1 7.81 14.57 L0 19.35 Z" }], ["path", { d: "M7.81 14.57 A4.9 4.9 0 0 1 7.81 9.48 M16.21 9.48 A4.9 4.9 0 0 1 16.21 14.57" }]],
  "drawio:butterfly-valve-1": [["ellipse", { cx: "12", cy: "12", rx: "1.22", ry: "1.22" }], ["path", { d: "M0 19.35 L0 4.65 L11.02 11.39 M12.98 12.61 L24 19.35 L24 4.65" }]],
  "drawio:check-valve-1": [["path", { d: "M0.73 19.55 L0.73 4.93 L24 19.55 L24 4.93" }], ["ellipse", { cx: "0.73", cy: "5.18", rx: "0.73", ry: "0.73" }], ["path", { d: "M21.81 16.63 L24 19.55 L20.47 18.94 L21.81 18.21 Z" }]],
  "drawio:check-valve-2": [["path", { d: "M0 4.93 L0 19.55 L23.27 4.93 L23.27 19.55" }], ["ellipse", { cx: "23.27", cy: "5.18", rx: "0.73", ry: "0.73" }], ["path", { d: "M2.19 16.63 L0 19.55 L3.53 18.94 L2.19 18.21 Z" }]],
  "drawio:gate-valve": [["path", { d: "M0 19.35 L0 4.65 L24 19.35 L24 4.65 Z" }]],
  "drawio:manual-operated-valve": [["path", { d: "M0 19.96 L0 5.27 L24 19.96 L24 5.27 Z" }], ["path", { d: "M12 12.61 L12 4.04 L19.35 4.04" }]],
  "drawio:three-way-valve": [["path", { d: "M4.65 21.67 L12 9.67 L24 2.33 L24 17.02 L0 2.33 L0 17.02 L12 9.67 L19.35 21.67 Z" }]],
  "drawio:relief-prv": [["path", { d: "M3.86 8.14 A8.14 8.14 0 0 1 20.14 8.14 Z M12 8.14 L12 24" }], ["rect", { x: "12", y: "8.14", width: "8.14", height: "3.25" }]],
  "drawio:safety-psv-1": [["path", { d: "M4.95 24 L10.29 15.24 L19.05 9.9 L19.05 20.57 L10.29 15.24 L15.62 24 Z M10.29 15.49 L10.29 0 M6.48 9.9 L14.1 4.83 M6.48 8.13 L14.1 3.05 M6.48 6.35 L14.1 1.27" }]],
  "drawio:diverter-valve": [["ellipse", { cx: "12", cy: "8.64", rx: "4.8", ry: "4.8" }], ["path", { d: "M0 8.64 L24 8.64 M24 3.84 L24 13.44 M0 3.84 L0 13.44 M19.2 20.16 L24 16.08 M21.6 18.24 L15.46 12" }]],
  "drawio:rotary-valve": [["ellipse", { cx: "12", cy: "12", rx: "4.8", ry: "4.8" }], ["path", { d: "M24 7.2 L24 16.8 M0 7.2 L0 16.8 M12 7.2 L12 16.8 M7.2 12 L16.8 12 M8.64 15.36 L15.36 8.64 M8.64 8.64 L15.36 15.36" }]],
  "drawio:y-type-strainer": [["path", { d: "M0 8.64 L24 8.64 M24 3.84 L24 13.44 M0 3.84 L0 13.44 M12 8.64 L21.6 18.24 M19.2 20.16 L24 16.08" }]],
  "drawio:condenser": [["ellipse", { cx: "12", cy: "12", rx: "9", ry: "9" }], ["path", { d: "M3 12 L6 12 L9 7.5 L15 16.5 L18 12 L21 12 M24 0 L0 24 M21 1.35 L24 0 L22.65 3 L22.5 1.5 Z" }]],
  "drawio:double-pipe-heat-exchanger": [["rect", { x: "1.33", y: "6.67", width: "18.67", height: "2.67" }], ["rect", { x: "1.33", y: "14.67", width: "18.67", height: "2.67" }], ["path", { d: "M0 8 L20 8 A4 4 0 1 1 20 16 L0 16 M2.67 5.33 L2.67 6.67 M2.13 5.33 L3.2 5.33 M0 7.47 L0 8.53 M0 15.47 L0 16.53 M2.67 17.33 L2.67 18.67 M2.13 18.67 L3.2 18.67 M18.67 9.33 L18.67 14.67" }]],
  "drawio:electric-heater": [["rect", { x: "10.29", y: "3.43", width: "13.71", height: "17.14" }], ["rect", { x: "0", y: "6", width: "6.86", height: "12" }], ["rect", { x: "12", y: "6.43", width: "10.29", height: "2.57" }], ["rect", { x: "12", y: "10.71", width: "10.29", height: "2.57" }], ["rect", { x: "12", y: "15", width: "10.29", height: "2.57" }], ["path", { d: "M6.86 7.71 L12 7.71 M6.86 12 L12 12 M6.86 16.29 L12 16.29 M14.57 6.43 L14.57 9 M17.14 6.43 L17.14 9 M19.71 6.43 L19.71 9 M14.57 10.71 L14.57 13.29 M17.14 10.71 L17.14 13.29 M19.71 10.71 L19.71 13.29 M14.57 15 L14.57 17.57 M17.14 15 L17.14 17.57 M19.71 15 L19.71 17.57 M4.29 10.29 L2.57 10.29 L2.57 13.71 L4.29 13.71 M2.57 12 L3.77 12" }]],
  "drawio:heater": [["ellipse", { cx: "12", cy: "12", rx: "9", ry: "9" }], ["path", { d: "M3 12 L6 12 L9 7.5 L15 16.5 L18 12 L21 12 M24 0 L0 24" }], ["path", { d: "M1.35 21 L0 24 L3 22.65 L1.5 22.5 Z" }]],
  "drawio:heat-exchanger-finned-tubes-fan": [["rect", { x: "0", y: "0", width: "24", height: "24" }], ["path", { d: "M9.6 18 L9.6 20.4 M14.4 18 L14.4 20.4 M16.8 18 L16.8 20.4 M12 18 L12 20.4 M7.2 18 L7.2 20.4 M3.6 19.2 L20.4 19.2 M14.4 2.88 L17.04 11.52 M9.6 2.88 L6.96 11.52" }], ["ellipse", { cx: "12", cy: "8.4", rx: "6", ry: "6" }]],
  "drawio:plate-and-frame-heat-exchanger": [["rect", { x: "3", y: "0", width: "18", height: "24" }], ["path", { d: "M5 0 L5 24 M7 0 L7 24 M9 0 L9 24 M11 0 L11 24 M13 0 L13 24 M15 0 L15 24 M17 0 L17 24 M19 0 L19 24 M2 0.6 L2 2.2 M2 21.8 L2 23.4 M22 0.6 L22 2.2 M22 21.8 L22 23.4 M2 1.4 L3 1.4 L21 22.6 L22 22.6 M2 22.6 L3 22.6 L21 1.4 L22 1.4" }]],
  "drawio:shell-and-tube-heat-exchanger-1": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M0 12 L4 12 L8 6 L16 18 L20 12 L24 12" }]],
  "drawio:spiral-heat-exchanger": [["ellipse", { cx: "12", cy: "12.6", rx: "10.8", ry: "10.8" }], ["ellipse", { cx: "12", cy: "12.6", rx: "8.4", ry: "8.4" }], ["ellipse", { cx: "14.4", cy: "12.6", rx: "0.72", ry: "0.72" }], ["ellipse", { cx: "9.6", cy: "12.6", rx: "0.72", ry: "0.72" }], ["path", { d: "M0 12.6 L9.6 12.6 M0 11.4 L0 13.8 M14.4 12.6 L24 12.6 M24 11.4 L24 13.8 M16.8 0.6 L19.2 0.6 M4.8 0.6 L7.2 0.6 M6 0.6 L6 5.4 L9.12 12.12 M18 0.6 L18 5.4 L14.88 12.12" }]],
  "drawio:chiller": [["path", { d: "M22.82 5.07 A0.77 1.99 0 1 1 22.82 11.2 L2.91 11.2 A0.77 1.99 0 1 1 2.91 5.07 Z" }], ["path", { d: "M22.82 14.26 A0.77 1.99 0 1 1 22.82 20.39 L2.91 20.39 A0.77 1.99 0 1 1 2.91 14.26 Z" }], ["path", { d: "M0.61 15.33 L1.99 15.33 M0.61 19.31 L1.99 19.31 M0.61 13.8 L0.61 16.86 M0 13.8 L0 16.86 M0.61 17.78 L0.61 20.85 M0 17.78 L0 20.85 M21.29 5.07 L21.29 3.77 M19.76 3.77 L22.82 3.77 M19.76 3.15 L22.82 3.15 M4.44 5.07 L4.44 3.77 M2.91 3.77 L5.97 3.77 M2.91 3.15 L5.97 3.15" }], ["rect", { x: "5.21", y: "11.2", width: "1.53", height: "3.06" }], ["rect", { x: "18.23", y: "11.2", width: "1.53", height: "3.06" }]],
  "drawio:cooling-tower": [["path", { d: "M2 24 L2 20 L7 0 L17 0 L22 20 L22 24 Z M22 20 L2 20" }]],
  "drawio:cooling-tower-wet-induced-draught": [["path", { d: "M2 24 L2 20 L7 0 L17 0 L22 20 L22 24 Z" }], ["path", { d: "M22 20 L2 20 M4.8 9 L12 9 L12 11 M10 11 L12 9 L14 11 M13.6 2.5 L14.8 6.2 M10.4 2.5 L9.2 6.2" }], ["ellipse", { cx: "12", cy: "5", rx: "3", ry: "3" }]],
  "drawio:cooler": [["ellipse", { cx: "11.33", cy: "12", rx: "10.67", ry: "10.67" }], ["path", { d: "M3.33 0 L3.33 24 M23.33 4 L14 4 L14 9.33 L18 9.33 L18 16 L14 16 L14 21.33 L23.33 21.33" }]],
  "drawio:fan": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M7.2 1.08 L23.28 7.92 M7.2 22.92 L23.28 16.08 M10.15 8.77 A3.6 0.72 49.48 0 1 11.94 11.98 A3.6 0.72 49.48 0 1 9.05 9.71 A3.6 0.72 49.48 0 1 7.26 6.5 A3.6 0.72 49.48 0 1 10.15 8.77 Z M9.05 14.34 A3.6 0.72 -49.91 0 1 11.92 12.05 A3.6 0.72 -49.91 0 1 10.15 15.26 A3.6 0.72 -49.91 0 1 7.28 17.55 A3.6 0.72 -49.91 0 1 9.05 14.34 Z" }], ["ellipse", { cx: "15.6", cy: "12", rx: "3.6", ry: "0.72" }]],
  "drawio:forced-flow-air-cooler": [["rect", { x: "0", y: "6.86", width: "24", height: "5.14" }], ["path", { d: "M7.89 15.77 L16.11 13.71 A1.03 1.03 0 1 1 16.11 15.77 L7.89 13.71 A1.03 1.03 0 1 0 7.89 15.77 Z" }], ["path", { d: "M3.43 6.86 L3.43 12 L1.71 17.14 M20.57 6.86 L20.57 12 L22.29 17.14" }]],
  "drawio:air-filter": [["rect", { x: "4.62", y: "0", width: "14.77", height: "24" }], ["path", { d: "M4.62 0 L19.38 24" }]],
  "drawio:ac-air-compressor": [["path", { d: "M1.87 10.12 L22.13 10.12 A9.42 9.42 0 0 1 22.13 20.01 L1.87 20.01 A9.42 9.42 0 0 1 1.87 10.12 Z" }], ["rect", { x: "1.92", y: "10.12", width: "20.12", height: "9.89" }], ["ellipse", { cx: "8.7", cy: "8.47", rx: "0.94", ry: "0.94" }], ["ellipse", { cx: "15.89", cy: "7.76", rx: "1.88", ry: "1.88" }], ["path", { d: "M8.5 7.55 L15.38 5.97 M8.71 9.44 L15.85 9.66 M4.11 10.12 L4.11 9.06 M3.05 9.06 L4.11 7.88 M4.11 3.99 L4.11 7.88 M3.28 5.97 L4.98 7.45 M3.52 5.33 L4.86 6.46 M3.66 4.7 L4.7 5.64 M20.83 10.12 L20.83 9.29" }], ["path", { d: "M3.05 6.82 L5.29 9.06 L3.05 9.06 Z M20.13 6.82 L21.54 6.82 L20.13 9.29 L21.54 9.29 Z" }]],
  "drawio:centrifugal-compressor": [["path", { d: "M4.11 19.03 L0 23.49 L20.57 23.49 L16.46 19.03" }], ["path", { d: "M0.21 9.09 A10.29 10.29 0 0 1 10.29 0.51 L24 0.51 L24 7.37 L20.04 7.37 A10.29 10.29 0 1 1 0.21 12.51" }]],
  "drawio:compressor": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M0 0 L3.48 3.48 M24 0 L20.52 3.48" }]],
  "drawio:reciprocating-compressor": [["path", { d: "M3.55 16.9 L3.55 7.1 L8.45 7.1 L8.45 10.29 L18.24 10.29 L18.24 16.9 Z" }], ["rect", { x: "0", y: "12.73", width: "3.43", height: "0.98" }], ["path", { d: "M18.24 12.73 L21.43 12.73 L21.43 12.37 L24 13.22 L21.43 14.08 L21.43 13.71 L18.24 13.71 Z" }]],
  "drawio:compressor-screw": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M6 1.68 L22.8 6.72 M6 22.32 L22.8 17.28 M6 10.8 L7.2 9.6 L9.6 12 L12 9.6 L14.4 12 L16.8 9.6 L18 10.8 M6 13.2 L7.2 12 L9.6 14.4 L12 12 L14.4 14.4 L16.8 12 L18 13.2" }]],
  "drawio:compressor-rotary": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M6 1.68 L22.8 6.72 M6 22.32 L22.8 17.28 M7.2 12 L16.8 12 M15.6 8.88 A4.8 4.8 0 0 1 15.6 15.12 M8.4 8.88 A4.8 4.8 0 0 0 8.4 15.12" }]],
  "drawio:compressor-diaphragm": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M6 1.68 L22.8 6.72 M6 22.32 L22.8 17.28 M6 1.68 A24 24 0 0 0 6 22.32" }]],
  "drawio:compressor-turbo": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M6 1.68 L22.8 6.72 M6 22.32 L22.8 17.28" }], ["ellipse", { cx: "12", cy: "12", rx: "6", ry: "6" }]],
  "drawio:gas-blower": [["path", { d: "M7.3 18.8 L3.32 23.12 L23.23 23.12 L19.25 18.8" }], ["path", { d: "M0 0.88 L13.28 0.88 A9.96 9.96 0 1 1 3.82 7.52 L0 7.44 Z" }], ["ellipse", { cx: "13.28", cy: "10.84", rx: "3.32", ry: "3.32" }]],
  "drawio:agitator-stirrer": [["path", { d: "M12 0 L12 20 M4 24 L4 16 L20 24 L20 16" }]],
  "drawio:agitator-anchor": [["path", { d: "M12 0 L12 24 M4 16 L4 21.6 A10 6 0 0 0 20 21.6 L20 16" }]],
  "drawio:agitator-propeller": [["path", { d: "M12 0 L12 21.8 M17.45 19.98 A2 2 0 1 1 17.45 23.61 L6.55 19.98 A2 2 0 1 0 6.55 23.61 Z" }]],
  "drawio:agitator-turbine": [["path", { d: "M12 0 L12 18.67" }], ["rect", { x: "4.89", y: "18.67", width: "3.56", height: "5.33" }], ["rect", { x: "15.56", y: "18.67", width: "3.56", height: "5.33" }], ["rect", { x: "8.44", y: "18.67", width: "3.56", height: "5.33" }], ["rect", { x: "12", y: "18.67", width: "3.56", height: "5.33" }]],
  "drawio:in-line-static-mixer": [["rect", { x: "0", y: "0", width: "24", height: "24" }], ["path", { d: "M4.2 9.6 L4.2 2.4 L19.8 21.6 L19.8 14.4" }]],
  "drawio:in-line-rotary-mixer": [["rect", { x: "1.26", y: "5.68", width: "22.74", height: "12.63" }], ["path", { d: "M0 12 L24 12 M2.53 10.74 L2.53 6.95 L10.74 17.05 L10.74 13.26 M12.63 10.74 L12.63 6.95 L20.84 17.05 L20.84 13.26" }]],
  "drawio:boiler-dome": [["rect", { x: "2", y: "4", width: "20", height: "20" }], ["path", { d: "M8 4 A4 4 0 1 1 16 4" }]],
  "drawio:firing-system-burner": [["rect", { x: "0", y: "18", width: "24", height: "6" }], ["path", { d: "M2.4 18 L12 0 L21.6 18 Z" }], ["path", { d: "M6 18 L12 7.2 L18 18" }]],
  "drawio:turbine": [["path", { d: "M3.6 8.4 L18 0 L18 24 L3.6 15.6 Z M20.4 12 L18 12" }]],
  "drawio:coriolis": [["rect", { x: "0", y: "0", width: "24", height: "24" }], ["path", { d: "M2.4 12 L6 12 L8.4 8.64 L13.2 15.36 L15.6 12 L19.2 12 M4.8 12 L8.4 12 L10.8 8.64 L15.6 15.36 L18 12 L21.6 12" }]],
  "drawio:magnetic": [["rect", { x: "0", y: "0", width: "24", height: "24" }]],
  "drawio:pitot-tube": [["rect", { x: "0", y: "0", width: "24", height: "24" }], ["path", { d: "M12 0 L12 12 L4.8 12" }]],
  "drawio:rotameter": [["path", { d: "M11.68 5.28 L0 12 L11.68 18.72" }], ["ellipse", { cx: "16", cy: "12", rx: "8", ry: "8" }]],
  "drawio:ultrasonic": [["rect", { x: "0", y: "0", width: "24", height: "24" }], ["path", { d: "M1.44 12 A2.88 2.88 0 0 1 6 12 A2.88 2.88 0 0 0 10.56 12 M13.44 12 A2.88 2.88 0 0 1 18 12 A2.88 2.88 0 0 0 22.56 12" }]],
  "drawio:venturi": [["path", { d: "M0 2.4 A28.8 28.8 0 0 0 24 2.4 L24 21.6 A28.8 28.8 0 0 0 0 21.6 Z" }]],
  "drawio:vortex": [["rect", { x: "0", y: "0", width: "24", height: "24" }], ["path", { d: "M2.4 2.4 L21.6 12 L2.4 21.6 Z" }]],
  "drawio:weir": [["path", { d: "M0 0 L0 24 L24 24 L24 0 L12 7.2 Z" }]],
  "drawio:stack-chimney": [["path", { d: "M7.2 24 L9.6 0 L14.4 0 L16.8 24 Z M4.8 24 L19.2 24" }]],
  "drawio:gas-flare": [["path", { d: "M4.8 24 L19.2 24 M12 6 A3.6 3.6 0 0 1 12 0 A3.6 3.6 0 0 1 12 6 Z" }], ["rect", { x: "9.6", y: "6", width: "4.8", height: "18" }]],
  "drawio:cyclone": [["path", { d: "M0 2.4 L0 7.2 L12 21.6 L24 7.2 L24 2.4 Z" }]],
  "drawio:spray-scrubber": [["path", { d: "M4 0 L20 0 L20 16 L12 24 L4 16 Z" }], ["path", { d: "M10 2 L12 0.1 L14 2 M12 0.1 L12 2" }]],
  "drawio:separator-electrostatic-precipitator": [["path", { d: "M4 0 L20 0 L20 16 L12 24 L4 16 Z" }], ["path", { d: "M7 14 L11 14 M11 12 L11 16 M13 12 L13 16 M13 14 L16 14" }]],
  "drawio:thermocouple": [["path", { d: "M3.22 0 L3.22 14.63 L12 23.41 L20.78 14.63 L20.78 0 M1.17 0.59 L1.17 2.34 M0.29 1.46 L2.05 1.46 M21.95 1.46 L23.71 1.46" }], ["ellipse", { cx: "12", cy: "23.41", rx: "0.59", ry: "0.59" }]],
  "drawio:thermistor-1": [["rect", { x: "4.32", y: "9.6", width: "15.36", height: "4.8" }], ["path", { d: "M0 12 L4.32 12 M19.68 12 L24 12 M7.2 19.2 L16.8 4.8 L19.68 4.8" }]],
  "drawio:electric-motor-ac": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M4.8 19.2 A4.32 4.32 0 0 1 12 19.2 A4.32 4.32 0 0 0 19.2 19.2" }]],
  "drawio:electric-motor-dc": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M4.8 19.2 L19.2 19.2" }]],
  "drawio:transformer": [["path", { d: "M0 0 L7.2 0 A3 3 0 0 1 7.2 6 A3 3 0 0 1 7.2 12 A3 3 0 0 1 7.2 18 A3 3 0 0 1 7.2 24 L0 24 M24 0 L16.8 0 A3 3 0 0 0 16.8 6 A3 3 0 0 0 16.8 12 A3 3 0 0 0 16.8 18 A3 3 0 0 0 16.8 24 L24 24" }]],
  "drawio:transformer-1": [["path", { d: "M0 23.25 L0 18 A3 3 0 0 1 6 18 A3 3 0 0 1 12 18 A3 3 0 0 1 18 18 A3 3 0 0 1 24 18 L24 23.25 M0 12.75 L24 12.75 M0 12 L24 12 M0 11.25 L24 11.25 M0 0.75 L0 6 A3 3 0 0 0 6 6 A3 3 0 0 0 12 6 A3 3 0 0 0 18 6 A3 3 0 0 0 24 6 L24 0.75" }]],
  "drawio:current-transformer-2": [["path", { d: "M8.57 0 L8.57 24 M13.71 12 L20.57 12 M16.46 10.97 L15.09 13.03 M18.51 10.97 L17.14 13.03" }], ["ellipse", { cx: "8.57", cy: "12", rx: "5.14", ry: "5.14" }]],
  "drawio:potential-transformer": [["path", { d: "M0 12 L7.8 12 M16.2 12 L24 12 M7.8 6 A3 3 0 0 1 7.8 12 A3 3 0 0 1 7.8 18 M16.2 6 A3 3 0 0 0 16.2 12 A3 3 0 0 0 16.2 18" }]],
  "drawio:adjustable-transformer": [["ellipse", { cx: "11.22", cy: "7.06", rx: "7.06", ry: "7.06" }], ["ellipse", { cx: "11.22", cy: "16.94", rx: "7.06", ry: "7.06" }], ["path", { d: "M2.89 11.86 L19.69 1.41 M20.12 1.98 L19.27 0.85 L21.11 0.42 Z" }]],
  "drawio:circuit-breaker": [["path", { d: "M19.2 13.92 L24 13.92 M17.92 12.64 L20.48 15.2 M20.48 12.64 L17.92 15.2 M0 13.92 L5.92 13.92 L18.24 8.8" }]],
  "drawio:isolator": [["path", { d: "M19.2 13.92 L24 13.92 M0 13.92 L5.92 13.92 L18.24 8.8 M19.2 12.64 L19.2 15.2" }]],
  "drawio:fuse": [["path", { d: "M8.32 12.32 L9.28 14.4 L14.46 12.26 L13.5 10.21 Z" }], ["path", { d: "M19.2 14.56 L24 14.56 M0 14.56 L5.92 14.56 L18.24 9.44" }]],
  "drawio:switch-disconnector": [["path", { d: "M19.2 14.08 L24 14.08 M19.2 13.12 L19.2 15.04 M0 14.08 L5.92 14.08 L18.24 8.96" }], ["ellipse", { cx: "18.24", cy: "14.08", rx: "0.96", ry: "0.96" }]],
  "drawio:dpdt": [["ellipse", { cx: "18.24", cy: "9.76", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "5.76", cy: "9.76", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "18.24", cy: "16.16", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "5.76", cy: "16.16", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "11.44", cy: "16", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "11.44", cy: "9.6", rx: "0.96", ry: "0.96" }], ["path", { d: "M0 9.76 L4.8 9.76 M0 16.16 L4.8 16.16 M19.2 9.76 L24 9.76 M19.2 16.16 L24 16.16 M12.16 9.12 L18.24 6.88 M12.16 15.52 L18.24 13.28" }], ["path", { d: "M15.04 8.16 L15.04 14.56" }]],
  "drawio:relay": [["rect", { x: "0", y: "8.36", width: "24", height: "7.27" }], ["path", { d: "M12 5.94 L12 8.36 M12 15.64 L12 18.06 M6.18 8.36 L6.18 15.64 M1.33 11.27 A0.97 2.18 0 0 1 3.03 12 A0.97 2.18 0 0 0 4.73 12.73" }]],
  "drawio:relay-coil": [["rect", { x: "0", y: "8.36", width: "24", height: "7.27" }], ["path", { d: "M12 5.94 L12 8.36 M12 15.64 L12 18.06" }]],
  "drawio:pushbutton-make": [["path", { d: "M0 19.52 L4.8 19.52 M19.2 19.52 L24 19.52 M5.76 16.96 L18.24 16.96 M12 3.52 L12 16.96" }], ["ellipse", { cx: "18.24", cy: "19.52", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "5.76", cy: "19.52", rx: "0.96", ry: "0.96" }]],
  "drawio:pressure-actuated": [["path", { d: "M0 8 L4.8 8 M19.2 8 L24 8 M6.72 8.32 L18.24 13.12 M11.84 10.4 L11.84 14.4" }], ["ellipse", { cx: "18.24", cy: "8", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "5.76", cy: "8", rx: "0.96", ry: "0.96" }], ["path", { d: "M9.28 16.96 A2.56 2.56 0 0 1 14.4 16.96 Z" }]],
  "drawio:temperature-actuated": [["path", { d: "M0 8 L4.8 8 M19.2 8 L24 8 M6.72 8.32 L18.24 13.12 M11.84 16.96 L11.84 15.04 L13.44 15.04 L13.44 13.44 L11.84 13.44 L11.84 10.4" }], ["ellipse", { cx: "18.24", cy: "8", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "5.76", cy: "8", rx: "0.96", ry: "0.96" }]],
  "drawio:flow-actuated": [["path", { d: "M0 8 L4.8 8 M19.2 8 L24 8 M6.72 8.32 L18.24 13.12" }], ["ellipse", { cx: "18.24", cy: "8", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "5.76", cy: "8", rx: "0.96", ry: "0.96" }], ["path", { d: "M11.84 10.4 L11.84 16.96 L14.4 16.96 L11.84 13.44" }]],
  "drawio:proximity-limit-switch": [["path", { d: "M0 12 L4.8 12 M19.2 12 L24 12 M18.24 10.72 L5.76 12 L14.72 14.88 L17.28 10.88 M3.2 12 L12 3.2 L20.8 12 L12 20.8 Z" }], ["ellipse", { cx: "18.24", cy: "12", rx: "0.96", ry: "0.96" }], ["ellipse", { cx: "5.76", cy: "12", rx: "0.96", ry: "0.96" }]],
  "drawio:motor-2": [["path", { d: "M3.6 9.6 L5.21 9.6 A7.2 7.2 0 0 1 18.79 9.6 L20.4 9.6 L20.4 14.4 L18.79 14.4 A7.2 7.2 0 0 1 5.21 14.4 L3.6 14.4 Z" }], ["path", { d: "M0 12 L3.6 12 M20.4 12 L24 12 M5.21 9.6 A7.2 7.2 0 0 0 5.21 14.4 M18.79 9.6 A7.2 7.2 0 0 1 18.79 14.4" }]],
  "drawio:line-cable": [["path", { d: "M0 12 L24 12" }], ["ellipse", { cx: "12", cy: "12", rx: "5.54", ry: "5.54" }]],
  "drawio:cable-group": [["path", { d: "M9.23 2.77 A2.77 2.77 0 0 1 12 0 A2.77 2.77 0 0 1 14.77 2.77 L14.77 21.23 A2.77 2.77 0 0 1 12 24 A2.77 2.77 0 0 1 9.23 21.23 Z" }], ["path", { d: "M0 3.88 L9.23 3.88 M0 7.94 L9.23 7.94 M0 12 L9.23 12 M0 16.06 L9.23 16.06 M0 20.12 L9.23 20.12 M14.77 3.88 L24 3.88 M14.77 7.94 L24 7.94 M14.77 12 L24 12 M14.77 16.06 L24 16.06 M14.77 20.12 L24 20.12" }]],
  "drawio:ampermeter": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M6.67 20 L17.33 4" }], ["path", { d: "M13.87 6.67 L17.33 4 L16.4 8.13 Z" }]],
  "drawio:galvanometer": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M12 20.53 L12 3.47 M10.67 7.2 L12 3.47 L13.33 7.2" }]],
  "drawio:oscilloscope": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M2.67 14.67 L6.67 9.33 L6.67 14.67 L10.67 9.33 L10.67 14.67 L14.67 9.33 L14.67 14.67 L18.67 9.33 L18.67 14.67 L20.67 12" }]],
  "drawio:surge-protector-2": [["path", { d: "M0 12 L6.17 12 M17.83 12 L24 12" }], ["rect", { x: "6.17", y: "5.14", width: "4.11", height: "13.71" }], ["rect", { x: "13.71", y: "5.14", width: "4.11", height: "13.71" }]],
  "drawio:terminal-board": [["rect", { x: "6", y: "0", width: "12", height: "24" }], ["path", { d: "M6 12 L18 12 M6 6 L18 6 M6 18 L18 18" }], ["ellipse", { cx: "12", cy: "3", rx: "0.8", ry: "0.8" }], ["ellipse", { cx: "12", cy: "9", rx: "0.8", ry: "0.8" }], ["ellipse", { cx: "12", cy: "15", rx: "0.8", ry: "0.8" }], ["ellipse", { cx: "12", cy: "21", rx: "0.8", ry: "0.8" }]],
  "drawio:monocell-battery": [["path", { d: "M0 12 L10.8 12 M13.2 4.8 L13.2 19.2 M13.2 12 L24 12" }], ["rect", { x: "9.84", y: "8.4", width: "0.96", height: "7.2" }]],
  "drawio:multicell-battery": [["path", { d: "M0 12 L4.8 12 M8.16 4.8 L8.16 19.2 M19.2 12 L24 12 M19.2 4.8 L19.2 19.2 M8.16 12 L9.36 12 M10.56 12 L11.76 12 M12.96 12 L14.16 12 M15.36 12 L15.84 12" }], ["rect", { x: "4.8", y: "8.4", width: "0.96", height: "7.2" }], ["rect", { x: "15.84", y: "8.4", width: "0.96", height: "7.2" }]],
  "drawio:light-bulb": [["ellipse", { cx: "12", cy: "12", rx: "10", ry: "10" }], ["path", { d: "M4.88 4.88 L19.12 19.12 M19.12 4.88 L4.88 19.12 M0 12 L2 12 M22 12 L24 12" }]],
  "drawio:lamp-1": [["ellipse", { cx: "12", cy: "12", rx: "12", ry: "12" }], ["path", { d: "M0 12 A12 12 0 1 1 24 12 L16.8 12 A4.8 4.8 0 0 0 7.2 12 Z" }]],
  "drawio:bell": [["path", { d: "M9.4 0 A8 8 0 1 1 9.4 24 Z M2.6 12 L9.4 12" }]],
  "drawio:buzzer": [["path", { d: "M3 0 A8 8 0 1 1 3 24 Z M14.2 8 L21 8 M14.2 16 L21 16" }]],
  "drawio:lift": [["rect", { x: "0", y: "0", width: "24", height: "24" }], ["ellipse", { cx: "14.4", cy: "6", rx: "3.6", ry: "3.6" }], ["path", { d: "M10.8 6 L10.8 14.4" }], ["rect", { x: "7.2", y: "14.4", width: "7.2", height: "7.2" }]],
};
